### ISSUE TITLE
在载入原酷Q C++SDK开发插件时出现问题

### ISSUE THREAD

**Issue by xCt0x** [iTXTech/mirai-native#1]
**怀疑** 是酷Q的c++ sdk会给函数名加上前缀和后缀的问题。一些关键函数如 _AppInfo_，_Initialize_，被修改后变成 __AppInfo@0_，__Initialize@4_ 。因为这些函数不能在对应的json文件里自定义，所以没办法被MiraiNative正常加载。希望dalao能快点解决啦:kissing:

**Comment by PeratX** [comment]
_AppInfo@0, _Initialize@4 是正确的 stdcall 导出函数，能够被正常加载
不能正常加载的是类似于 _AppInfo@0_0 这样的函数，请检查编译参数
目前移植的CQHTTP官方编译出来的就是 @x_0 这样的，重新编译就成了 @x ，能够正常使用。

如果可以的话，请附上无法使用的插件，将会调查

**Comment by xCt0x** [comment]
@PeratX 我测试的是这个[插件](https://is.gd/L1yOOM)，它会处理_!motd_ 开头的信息。

**Comment by PeratX** [comment]
其提供源代码，无源代码无法调查

**Comment by xCt0x** [comment]
@PeratX 你好，我在发这个issue前已经试过了在json中修改这些函数，
`_XXX __XXX,___XXX,___XXX@X` 都没有作用。
在看到你的回复后我又尝试把这个dll放到原酷Q里使用，居然失败了，提示`AppInfo函数不存在或错误。` 之后我用易语言的SDK编译了演示插件，测试发现经酷Q编译成cpk的插件 在tmp/capp下释放的文件已经被修改了，它的CRC32和原dll是不同的，并且在有原json文件的情况下，它不能被mirai-native或者酷Q载入(AppInfo)。不知道你之前有没有测试过现有的酷Q插件。酷Q看来有一套防盗插件机制？这是我这个dll不能在mirai-native下使用的原因？如果是的话，有方法解决吗？

**Comment by PeratX** [comment]
我测试了CQ官方插件，点歌插件，图灵机器人，都是从capp提取的dll，可以直接使用

**Comment by PeratX** [comment]
测试了下，可能是最新酷Q修改过了，提取的我这也不能正常用了，原来的可以
CPK文件还是原来的，但是解出来的dll不一样了
