### ISSUE TITLE
载入酷Q Native.SDK开发插件时似乎存在问题

### ISSUE THREAD

**Issue by smyhw** [iTXTech/mirai-native#10]
使用的C#SDK
SDK开源位置 https://github.com/Jie2GG/Native.Framework
插件开源位置 https://github.com/smyhw/KQ-WelcomeMessage

有关日志

- [Plugin Manager] loading plugin MiraiNative  
- [Plugin Manager] successfully loaded plugin MiraiNative version 1.7.0 by iTX Technologies  
- [Plugin Manager] 强大的 Mirai 原生插件加载器  
- [MiraiNative] 正在加载 Z:\work_temp\新建文件夹\qq_robot\plugins\MiraiNative\CQP.dll  
- [MiraiNative] Native Plugin (w json) 进群欢迎语 has been loaded with code 126  
- [MiraiNative] Mirai Native 正启用所有 DLL 插件。  
- **-->npm list**  
- [Command] 共加载了 0 个 Mirai Native 插件  

除此之外，控制台也没有输出任何报错
插件似乎并没有被加载
使用流泪猫猫头加载dll后，控制台输出

- [MiraiNative] Native Plugin (w json) 进群欢迎语 has been loaded with code 126
- -->npm list
- [Command] 共加载了 0 个 Mirai Native 插件

插件似乎仍未加载。。。

如下,附上完整日志

- PS Z:\work_temp\新建文件夹\qq_robot> .\miraiOK_windows_386.exe
- [12:19:54.7194] I MiraiOK 20200629.160938 running at windows-386
- [12:19:54.7204] I 此程序以Affero GPL3.0协议发布，使用时请遵守协议
- [12:19:54.7214] I 代码库: github.com/LXY1226/MiraiOK gitee.com/LXY1226/MiraiOK
- [12:19:54.8560] I JRE: openjdk version "1.8.0_252"
- [12:19:54.8560] I JRE: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
- [12:19:54.8560] I JRE: OpenJDK Client VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
- [12:19:54.8560] I 删除.lastupdate来在下次强制检查更新
- [12:19:54.8560] I 启动Mirai...
- Using proxy: null
- You are running Mirai-Console-Wrapper under Z:\work_temp\新建文件夹\qq_robot
- All additional libraries are located at Z:\work_temp\新建文件夹\qq_robot\libraries
- Starting Mirai Console Pure, reset by clear /content/
- Starting version check...
- Fetching Newest Core Version ..
- Stay on current version.
- Fetching Newest Console Version of Pure
- Stay on current version.
- Version check complete, starting Mirai
- shadow-Protocol:Z:\work_temp\新建文件夹\qq_robot\content\mirai-core-qqandroid-1.1.3.jar
- Console        :Z:\work_temp\新建文件夹\qq_robot\content\mirai-console-0.5.2.jar
- Root           :Z:\work_temp\新建文件夹\qq_robot/
-  12:19:55 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console now running under Z:\work_temp\新建文件夹\qq_robot
-  12:19:55 [INFO] [Mirai 0.5.2 Pkmon] Get news in github: https://github.com/mamoe/mirai
-  12:19:55 [INFO] [Mirai 0.5.2 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
-  12:19:55 [INFO] [Mirai 0.5.2 Pkmon] Powered by Mamoe Technologies and contributors
-  12:19:55 [INFO] [Plugin Manager] 开始加载Z:\work_temp\新建文件夹\qq_robot/plugins/下的插件
-  12:19:55 [INFO] [Plugin Manager] loading plugin MiraiNative
-  12:19:55 [INFO] [Plugin Manager] successfully loaded plugin MiraiNative version 1.7.0 by iTX Technologies
-  12:19:55 [INFO] [Plugin Manager] 强大的 Mirai 原生插件加载器
-  12:19:55 [INFO] [MiraiNative] 正在加载 Z:\work_temp\新建文件夹\qq_robot\plugins\MiraiNative\CQP.dll
-  12:19:55 [INFO] [Plugin Manager] 加载了1个插件
-  12:19:55 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console 启动完成
-  12:19:55 [INFO] [Mirai 0.5.2 Pkmon] "login qqnumber qqpassword " to login a bot
-  12:19:55 [INFO] [Mirai 0.5.2 Pkmon] "login qq号 qq密码 " 来登录一个BOT
-  12:19:55 [INFO] [Bot Login] login...
-  12:19:56 [INFO] [MiraiNative] Native Plugin (w json) 进群欢迎语 has been loaded with code 126
-  12:19:56 [INFO] [BOT 3234570937] Logging in...
-  12:19:56 [INFO] [NETWORK] Connected to server msfwifi.3g.qq.com:8080
-  12:19:56 [INFO] [NETWORK] Send: wtlogin.login
-  12:19:56 [INFO] [NETWORK] Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
-  12:19:56 [INFO] [NETWORK] Send: wtlogin.login
-  12:19:56 [INFO] [NETWORK] Recv: LoginPacketResponse.Success
-  12:19:56 [INFO] [NETWORK] Login successful
-  12:19:56 [INFO] [NETWORK] Send: StatSvc.register
-  12:19:56 [INFO] [NETWORK] Recv: Response(StatSvc.register)
-  12:19:56 [INFO] [NETWORK] 开始加载好友信息
-  12:19:56 [INFO] [NETWORK] 开始加载群组列表与群成员列表
-  12:19:56 [INFO] [NETWORK] Send: friendlist.getFriendGroupList
-  12:19:56 [INFO] [NETWORK] Send: friendlist.GetTroopListReqV2
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetFriendGroupList.Response
-  12:19:57 [INFO] [NETWORK] 正在加载好友列表 14/14
-  12:19:57 [INFO] [NETWORK] 好友列表加载完成, 共 14个
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetFriendGroupList.Response
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: OidbSvc.0x88d_7
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:57 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:58 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:58 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:58 [INFO] [NETWORK] Send: friendlist.GetTroopMemberListReq
-  12:19:58 [INFO] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
-  12:19:58 [INFO] [NETWORK] 群组列表与群成员加载完成, 共 13个
-  12:19:58 [INFO] [NETWORK] Awaiting ConfigPushSvc.PushReq
-  12:19:58 [INFO] [NETWORK] Syncing friend message history...
-  12:19:58 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
-  12:19:58 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
-  12:19:58 [INFO] [NETWORK] Syncing friend message history: Success
-  12:19:58 [INFO] [BOT 3234570937] Login successful
-  12:19:58 [INFO] [MiraiNative] Mirai Native 正启用所有 DLL 插件。
-  12:19:58 [INFO] [Command] 3234570937 login successes
-  12:19:59 [INFO] [NETWORK] Received unknown commandName: ConfigPushSvc.PushDomain
-  12:20:00 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
-  12:20:00 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
-  12:20:00 [INFO] [NETWORK] ConfigPushSvc.PushReq: Success
- **npm list**
-  _12:20:09 [INFO] [Command] 共加载了 0 个 Mirai Native 插件_
-  _12:20:18 [INFO] [MiraiNative] Native Plugin (w json) 进群欢迎语 has been loaded with code 126_
- **npm list**
-  _12:20:24 [INFO] [Command] 共加载了 0 个 Mirai Native 插件_

**Comment by PeratX** [comment]
加载显示code 126表示缺少依赖的dll，请使用命令查看该插件依赖哪些dll并将它们放到MiraiNative的libraries文件夹中。

**Comment by smyhw** [comment]
额，可能我比较小白。。。
请问该如何确定插件缺失的依赖呢,
我使用软件对dll进行分析，它似乎不缺少任何依赖...
![image](https://user-images.githubusercontent.com/47166461/89319925-65956100-d6b3-11ea-941b-c688ac094f94.png)


附上dll文件
[app.zip](https://github.com/iTXTech/mirai-native/files/5023291/app.zip)

dalao帮忙看看?

**Comment by PeratX** [comment]
莫非是.NET Framework的问题？白天我看看

**Comment by smyhw** [comment]
app.json
[app.zip](https://github.com/iTXTech/mirai-native/files/5023548/app.zip)

**Comment by Hellobaka** [comment]
不能使用中文路径，用中文路径会返回126

**Comment by PeratX** [comment]
> app.json
> [app.zip](https://github.com/iTXTech/mirai-native/files/5023548/app.zip)

试试楼上说的，不要用中文路径

**Comment by smyhw** [comment]
success!
感谢dalao们!
是中文路径的问题qwq

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/89373469-534f0d80-d71b-11ea-8905-502e3ddfab0d.png)
不能加载中文路径的bug将在下个版本修复
