### ISSUE TITLE
获取群成员列表时，加群时间字段为0

### ISSUE THREAD

**Issue by AlexanderMisel** [iTXTech/mirai-native#102]
**描述这个Bug**
在使用coolq-http-api获取群成员列表时，拿到的join_time和last_send_time返回为0，不符合实际情况。

**复现步骤**
- 按照Wiki中的步骤安装coolq-http-api
- 请求获取群成员列表接口，http://127.0.0.1:5700/get_group_member_list?group_id=xxxxxxxx

**期望的行为**
正确返回join_time和last_send_time

**截图和日志**
日志不便提供

**运行环境**
 - 操作系统：Windows Server 2016 Datacenter
 - `mirai core` 版本：1.3.0
 - `mirai console` 版本：1.0-M4
 - `mirai native` 版本：1.9.2
 - `Java` 运行时版本：11.0.8 x86

**更多信息**
我群不定期需要检查群成员名片，群名片需要请求外部HTTP接口判断是否符合规则。加群时间字段有助于增量检查群名片。

**Comment by PeratX** [comment]
mirai不支持获取。
