### ISSUE TITLE
群聊无法发送某些固定内容的消息

### ISSUE THREAD

**Issue by Pika-Lee** [iTXTech/mirai-native#103]
**描述这个Bug**
bot发送某些固定内容的消息时，会无法发出，修改消息中的局部内容后，便可正常发送。

**复现步骤**

当发现bot无法发送某些特定的消息时，会出现下面截图中的错误提示。

出现该问题时，对上述消息中的局部文字稍作修改后，bot便可正常发出

**期望的行为**
希望bot能够正常发送固定内容的消息

**截图和日志**

![ERROR6](https://user-images.githubusercontent.com/23114990/96623613-33081580-133e-11eb-9677-205a902639b8.png)

**运行环境**
 - 操作系统：Windows Server 2016
 - `mirai core` 版本：1.3.0
 - `mirai console` 版本：1.0-M4
 - `mirai native` 版本：1.9.2
 - `Java` 运行时版本：1.8.0 252

**更多信息**
不太清楚截图中ERROR的具体原因是什么，但是这个问题确实出现过很多次了（当发现某些特定的文本无法发出时，稍作修改后便可正常发送，甚至再改回原来的内容也能正常发送= =）

**Comment by PeratX** [comment]
请向`mirai-core`反馈该问题。
