### ISSUE TITLE
处理加群请求时遇到问题

### ISSUE THREAD

**Issue by DreamPrism** [iTXTech/mirai-native#106]
RT，使用Native.Sdk，在Event_GroupAddRequest中使用e.Request.SetGroupAddRequest处理加群请求时出现错误
**复现步骤**
![image](https://user-images.githubusercontent.com/52944979/97794272-c2f96980-1c32-11eb-94ec-ecb56d9fe6ba.png)
如图，事件能够正常被触发
**期望的行为**
机器人能够根据给定条件通过/拒绝请求，拒绝时能给出附加信息

**截图和日志**
![image](https://user-images.githubusercontent.com/52944979/97794215-f4be0080-1c31-11eb-9e38-13790de3ae6b.png)

**运行环境**
 - 操作系统：Windows Server 2012 R2 Standard
 - `mirai console` 版本：1.3.0
 - `mirai native` 版本：1.7.0
 - `Java` 运行时版本：1.8.0_261

**Comment by PeratX** [comment]
QQ的id怎么是0呢？
`mirai`不支持拒绝消息。

**Comment by DreamPrism** [comment]
对，我也挺奇怪这个0的，可能是由于加群的账号被过滤了？

**Comment by PeratX** [comment]
应该是传参的问题吧

**Comment by hksz** [comment]
那里下的Native C#Sdk 求出处

**Comment by PeratX** [comment]
如能提供更多信息将被重新开启。
