### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by z594024037** [iTXTech/mirai-native#108]
**描述这个Bug**
运行一段时间后出现Microsoft visual c++ runtime library弹窗提示abnormal program termination弹窗后 native内的天枢群管家插件停止工作 控制台继续输出聊天记录bot未掉线
**复现步骤**
mirai-console-loader1.0.0运行几十个小时（最近三次运行时间70h.70h.40h）后就会出现这个提示
**期望的行为**
希望能帮忙分析解决此问题 
**截图和日志**
![pic](https://user-images.githubusercontent.com/67503218/98223487-1547cc80-1f4a-11eb-9d15-de959e625f32.jpg)

**运行环境**
 - 操作系统：Windows server 2019
 - `mirai core` 版本：1.3.1
 - `mirai console` 版本：1.0-RC-dev-29
 - `mirai native` 版本：1.9.3
 - `Java` 运行时版本：1.8.0_261

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
很奇怪，应该是某个插件触发的报错

**Comment by PeratX** [comment]
请问问题是否解决？

**Comment by z594024037** [comment]
> 请问问题是否解决？

现在在靠重启维持运行

只有一个天枢群管插件，这个几十个小时就崩溃的qq管理了四十多个群，另一个qq管理了两个群连续运行了330+小时刚刚才挂了（原因看上去是掉线重连连了几个小时 但连不上了 ）
![diaoxian](https://user-images.githubusercontent.com/67503218/99083950-3057b380-25be-11eb-9617-da90e6e6602f.png)
（启动方式都是loader1.0.0 复制粘贴成的两份）
