### ISSUE TITLE
CacheManager 的设计问题

### ISSUE THREAD

**Issue by mrhso** [iTXTech/mirai-native#11]
按照源代码来看，似乎只有临时消息能够更新 senders。如果是这样的话，getStrangerInfo 就只能用于对 Bot 触发临时消息的 QQ。

**Comment by PeratX** [comment]
是的，mirai不支持随意获取用户信息，这是对用户隐私的保护，详细请查看mirai项目的信息。

**Comment by mrhso** [comment]
但是如果是触发过群消息或者是私聊消息的 QQ，这样算是随意获取吗？

**Comment by PeratX** [comment]
用户发起的会话就可以获取，这是mirai的设计，与本项目无关。
