### ISSUE TITLE
接收图片直链

### ISSUE THREAD

**Issue by wlt233** [iTXTech/mirai-native#112]
**特性描述**

看了 [`ChainCodeConverter.kt`](https://github.com/iTXTech/mirai-native/blob/master/src/main/kotlin/org/itxtech/mirainative/message/ChainCodeConverter.kt#L210) 代码，似乎不支持接收到的图片获取文件真实 `url`。请问一下这是由于 `mirai` 的特性导致的么？

**Comment by PeratX** [comment]
需要通过API调用才能下载图片，不能获取图片的url

**Comment by wlt233** [comment]
抱歉还是打扰了，请问一下这里的 api 指的是哪一层的什么接口？
另：参考 [`mirai` 源码](https://github.com/mamoe/mirai/blob/63919554593c39acd9af0d92cb61c9b0eeec8ee5/mirai-core/src/commonMain/kotlin/message/imagesImpl.kt#L34)得知其有做直链处理，并且按其格式使用图片 id 拼成的 url 就是直链。所以请问一下这个拼接整合的步骤可否通过 `native` 部分实现？
