### ISSUE TITLE
cqhttp的dll在mirai native中ws反向代理异常

### ISSUE THREAD

**Issue by anaivebird** [iTXTech/mirai-native#115]
# 描述这个Bug
cqhttp的dll在mirai native中无法加载，开启ws反向代理报错如下：

2020-12-20 18:11:05 I/MiraiNative: [CQHTTP 反向WS] 开启反向 WebSocket 客户端（Event）成功，开始连接 ws://127.0.0.1:8080/cqhttp/ws/
2020-12-20 18:11:05 I/MiraiNative: [CQHTTP 反向WS] 开启反向 WebSocket 客户端（API）成功，开始连接 ws://127.0.0.1:8080/cqhttp/ws/
2020-12-20 18:11:07 W/MiraiNative: [CQHTTP 反向WS] 反向 WebSocket（Event）客户端连接失败或异常断开，将在 3000 毫秒后尝试重连
2020-12-20 18:11:07 W/MiraiNative: [CQHTTP 反向WS] 反向 WebSocket（API）客户端连接失败或异常断开，将在 3000 毫秒后尝试重连

无限循环

# 复现步骤
使用最新的mirai native 和 mirai 2.0-M1-1版本

**截图和日志**
![image](https://user-images.githubusercontent.com/29398611/102710690-072def80-42ef-11eb-97ac-09dc4cb1bfad.png)

# CQHTTP配置为

{
    "$schema": "https://cqhttp.cc/config-schema.json",
    "host": "0.0.0.0",
    "port": 5700,
    "use_http": true,
    "ws_host": "127.0.0.1",
    "ws_port": 6700,
    "use_ws": true,
    "ws_reverse_url": "ws://127.0.0.1:8080/cqhttp/ws",
    "enable_heartbeat": true,
    "ws_reverse_reconnect_interval": 3000,
    "ws_reverse_reconnect_on_code_1000": true,
    "use_ws_reverse": true,
    "post_url": "",
    "access_token": "",
    "secret": "",
    "post_message_format": "string",
    "serve_data_files": false,
    "update_source": "global",
    "update_channel": "stable",
    "auto_check_update": false,
    "auto_perform_update": false,
    "show_log_console": true,
    "log_level": "info",
    "show_log_console": false,
    "disable_coolq_log": false
}

# 运行环境
 - 操作系统：Windows 10
 - `mirai core` 版本：mirai-console-2.0-M1-1
 - `mirai console` 版本：mirai-core-all-2.0-M1-1
 - `mirai native` 版本：mirai-native-1.9.5
 - `Java` 运行时版本：openjdk version "11.0.9.1" 2020-11-04 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1) OpenJDK Client VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

**Comment by PeratX** [comment]
插件配置问题，这里无法提供支持。
