### ISSUE TITLE
调试日志没了

### ISSUE THREAD

**Issue by dragon0629** [iTXTech/mirai-native#116]
# 警告：请认真填写以下栏目，如果不符合要求，将直接被关闭。编辑完请删除此行。

**描述这个Bug**
信息日志显示正常
调试日志貌似不显示了

**复现步骤**
插件里的日志_调试 基本都不显示了

**期望的行为**
显示调试日志

**截图和日志**
好像无需截图

**运行环境**
 - 操作系统：[例子：Windows 10 2004]
 - `mirai core` 版本：[例子：2.0M1]
 - `mirai console` 版本：[例子：2.0M1]
 - `mirai native` 版本：[例子：1.9.5]
 - `Java` 运行时版本：[例子：11.0.7 x86]

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
嗯？没懂

**Comment by dragon0629** [comment]
emmmmm这么说吧
cq.日志_信息的日志 正常显示 I/mirainative
cq.日志_调试的日志 之前1.9.2时代可以显示D/mirainative的，到1.9.5之后，这个调试日志没了，窗口里显示不出来。

**Comment by PeratX** [comment]
这个可能是mirai console默认不显示debug信息了，尝试修改下mirai的配置

**Comment by dragon0629** [comment]
# 日志输出等级 可选值: ALL, VERBOSE, DEBUG, INFO, WARNING, ERROR, NONE
defaultPriority: INFO
# 特定日志记录器输出等级
loggers: 
  example.logger: NONE
  console.debug: NONE
  Bot: ALL

是这里嘛0_0,是否只能选INFO或者ALL啊，可以设置只显示INFO 和 DEBUG么
