### ISSUE TITLE
JAVA Encoding 乱码

### ISSUE THREAD

**Issue by zx900930** [iTXTech/mirai-native#117]
**描述这个Bug**
非中文系统托盘区插件菜单乱码。

**复现步骤**
只需要一个非中文的操作系统即可复现，托盘区的插件设置基本不能用全是乱码。
而且Windows的非Unicode语言很早前就已经改为了简体中文。
batch可以通过chcp 936正常显示中文，可是java不行。
用-Dfile.encoding=GB18030 或者 -Dfile.encoding=GBK 均无效。
完整启动脚本
```
@echo off
taskkill /F /IM java.exe
cd "%PATH_MCL%\mcl"
chcp 936
set JAVA_BINARY=java
%JAVA_BINARY% -Dfile.encoding=GB18030 -jar mcl.jar %*
exit /b
```
启动是正常的
![image](https://user-images.githubusercontent.com/734749/103034158-8ed06400-4564-11eb-9f29-b44f675cad3f.png)

**期望的行为**
能设定java的codepage并且正常显示中文的菜单。

**截图和日志**
如图所示
![image](https://user-images.githubusercontent.com/734749/103031467-2aaaa180-455e-11eb-959a-d4f8b89fde25.png)

**运行环境**
 - 操作系统：Windows Server 2016 1607 x64
 - `mirai core` 版本：2.0-M1-1
 - `mirai console` 版本：2.0-M1-1
 - `mirai native` 版本：[1.9.5](https://github.com/iTXTech/mirai-native/releases/tag/v1.9.5)
 - `Java` 运行时版本：openjdk 11.0.9.1 2020-11-04

**Comment by PeratX** [comment]
-Dfile.encoding=UTF8
json文件的编码也修改试试

**Comment by zx900930** [comment]
-Dfile.encoding=UTF8
json UTF-8
主程序也乱码了
![image](https://user-images.githubusercontent.com/734749/103273529-ceada600-49bf-11eb-9b61-0af72e95d97a.png)

**Comment by PeratX** [comment]
emmmm 这确实不太知道怎么解决

**Comment by PeratX** [comment]
修改json编码
