### ISSUE TITLE
插件无法找到CQP.dll中的CQ_getRecord

### ISSUE THREAD

**Issue by Pika-Lee** [iTXTech/mirai-native#118]
**描述这个Bug**
某插件在接收到群内语音消息后报错，ERROR内容见截图

**复现步骤**
当群内收到群员发送的语音消息后出错

**期望的行为**
希望能够正常接收并处理群内的语音消息

**截图和日志**

[QQ截图20210101000203](https://user-images.githubusercontent.com/23114990/103418789-308e2b80-4bcb-11eb-8f0b-ca34432d72b9.png)

**运行环境**
 - 操作系统：[例子：Windows Server2016]
 - `mirai core` 版本：[例子：2.0-M1-1]
 - `mirai console` 版本：[例子：2.0-M1-1]
 - `mirai native` 版本：[例子：1.9.5]
 - `Java` 运行时版本：[例子：N/A]

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
mirai不支持接受语音消息，还有图裂了

**Comment by PeratX** [comment]
接收语音消息，请使用getRecordV2，getRecord没见到其实现所以没做

**Comment by Pika-Lee** [comment]
> mirai不支持接受语音消息，还有图裂了
> 接收语音消息，请使用getRecordV2，getRecord没见到其实现所以没做

感谢修复，今天又遇到了一次这个问题。主要还是因为旧插件已停止维护，使用了旧的调用方法所致。还请麻烦您在native后续版本中能兼容支持一下~
![Uploading QQ截图20210117184158.png…]()
