### ISSUE TITLE
卸载多个插件时会报错

### ISSUE THREAD

**Issue by Amazefcc233** [iTXTech/mirai-native#119]
**描述这个Bug**
在退出mirai时，若加载了多个插件则仅会卸载第一个被加载的插件然后报错
（无论是.dev.dll还是.dll都会出现此问题，但如果只加载了一个插件则不会报错）

**复现步骤**
1. 加载>=2个插件
2. 输入exit
3. 出现报错

**期望的行为**
插件应被一个个卸载，并显示卸载成功的log

**截图和日志**
![E76F9D3F-6343-4014-B1DB-3E9B07940165.jpeg](https://i.loli.net/2021/01/01/whqeDAH1csjvWJK.jpg)
(https://i.loli.net/2021/01/01/whqeDAH1csjvWJK.jpg)

**运行环境**
 - 操作系统：Windows Server 2012 R2
 - `mirai core` 版本：2.0-M2-1
 - `mirai console` 版本：2.0-M2-1-dev-1
 - `mirai native` 版本：1.9.6
 - `Java` 运行时版本：11.0.9.1 x86

**Comment by PeratX** [comment]
了解，会修复
