### ISSUE TITLE
解析xmlCQ码时报错

### ISSUE THREAD

**Issue by lulu666lulu** [iTXTech/mirai-native#12]
14:08:03 [ERROR] [MiraiNative] CQ消息解析失败：[CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="[回执消息]" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>]，索引：140
 14:08:03 [ERROR] [MiraiNative] CQ消息解析失败：[CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="[回执消息]" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>]，索引：410

**Comment by lulu666lulu** [comment]
jsonmirai报错
Exception in thread "DefaultDispatcher-worker-4" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.Collections$SingletonList.get(Collections.java:4817)
        at org.itxtech.mirainative.message.ChainCodeConverter.toMap(ChainCodeConverter.kt:62)
        at org.itxtech.mirainative.message.ChainCodeConverter.toMessageInternal(ChainCodeConverter.kt:71)
        at org.itxtech.mirainative.message.ChainCodeConverter.codeToChain(ChainCodeConverter.kt:221)
        at org.itxtech.mirainative.bridge.MiraiBridge$sendGroupMessage$$inlined$call$lambda$1.invokeSuspend(MiraiBridge.kt:140)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by PeratX** [comment]
请给出完整消息，无法复现

**Comment by lulu666lulu** [comment]
被github弄没了。

**Comment by lulu666lulu** [comment]
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="[回执消息]" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>

**Comment by lulu666lulu** [comment]
`<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="[回执消息]" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>`

**Comment by lulu666lulu** [comment]
`[CQ:json,data={"app":"com.tencent.qqpay.qqmp.groupmsg","desc":"","view":	"groupPushView","ver":"1.0.0.3","prompt":"主人：","appID":	"","sourceName":"","actionData":"","actionData_A":	"","sourceUrl":"","meta":{"groupPushData":	{"time":"","cancel_url":"http:\/\/www.baidu.com","fromIcon":"","report_url":"","bannerLink":"","fromName":"name","summaryTxt":"※※调教时请注意使用频率，您的滥用可能会导致bot账号被封禁，欢","bannerImg":"http:\/\/gchat.qpic.cn\/gchatpic_new\/0\/0-0-39742153EFC566521C293CC13A526D98\/0?","bannerTxt":"主人：","item1Img":""}},"config":{"forward":	0,"showSender":1},"text":"快看过来！","sourceAd":""}]`

**Comment by PeratX** [comment]
你忘记CQ码的转义
```
 private fun String.escape(c: Boolean = false): String {
        var s = replace("&", "&amp;")
            .replace("[", "&#91;")
            .replace("]", "&#93;")
        if (c) {
            s = s.replace(",", "&#44;")
        }
        return s
    }

    private fun String.unescape(): String {
        return replace("&amp;", "&")
            .replace("&#91;", "[")
            .replace("&#93;", "]")
    }
```

**Comment by lulu666lulu** [comment]
原本是转义，不行才换的

**Comment by lulu666lulu** [comment]
我是词库插件直接教的，后台记录原数据就是转义的但是也是报错

**Comment by lulu666lulu** [comment]
&#91CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="&#91回执消息&#931" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>&#931

**Comment by lulu666lulu** [comment]
`&#91CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="&#91回执消息&#931" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>&#931`

**Comment by PeratX** [comment]
> `&#91CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="&#91回执消息&#931" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>&#931`

这个不报错，但是不会发出去，正在看

**Comment by lulu666lulu** [comment]
`14:51:24 [ERROR] [MiraiNative] CQ消息解析失败：[CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="[回执消息]" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>]，索引：140
 14:51:24 [ERROR] [MiraiNative] CQ消息解析失败：[CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="[回执消息]" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>]，索引：410`
我这里还是这个。。。，我换个插件看看

**Comment by PeratX** [comment]
索引都给出了，你可以看到那个位置的哪个字符有问题

**Comment by lulu666lulu** [comment]
这个索引是错误字符是吧，好的

**Comment by PeratX** [comment]
> 这个索引是错误字符是吧，好的

代码确实有点问题，部分CQ码不会转义回去

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/89381617-09225800-d72c-11ea-93a1-1647f1f0e9f3.png)

我这测试了可以发送了，下个版本修复

**Comment by lulu666lulu** [comment]
好的，谢谢

**Comment by PeratX** [comment]
xml可以发，json发了不显示，但是转义都正常了，考虑其他原因吧。

**Comment by cucibala** [comment]
我也是转了义以后发送不报错了，但是发送不显示。请问这个解决了吗

**Comment by PeratX** [comment]
> 我也是转了义以后发送不报错了，但是发送不显示。请问这个解决了吗

这个还得向mirai汇报一下，现在发送的是正常的

**Comment by m839336369** [comment]
> > 我也是转了义以后发送不报错了，但是发送不显示。请问这个解决了吗
> 
> 这个还得向mirai汇报一下，现在发送的是正常的

能给我两个可行的xml与json么？我不管转义还是没转义都无法发送成功
另外[CQ:xml data=xxx]这个地方的[]需要转义么？
![image](https://user-images.githubusercontent.com/30934916/90105674-e241d280-dd78-11ea-898a-43d930e966fd.png)

**Comment by PeratX** [comment]
> > > 我也是转了义以后发送不报错了，但是发送不显示。请问这个解决了吗
> > 
> > 
> > 这个还得向mirai汇报一下，现在发送的是正常的
> 
> 能给我两个可行的xml与json么？我不管转义还是没转义都无法发送成功
> 另外[CQ:xml data=xxx]这个地方的[]需要转义么？
> ![image](https://user-images.githubusercontent.com/30934916/90105674-e241d280-dd78-11ea-898a-43d930e966fd.png)

xml测试可以发送，json我用kotlin代码都发不出去。。。

**Comment by m839336369** [comment]
> > > > 我也是转了义以后发送不报错了，但是发送不显示。请问这个解决了吗
> > > 
> > > 
> > > 这个还得向mirai汇报一下，现在发送的是正常的
> > 
> > 
> > 能给我两个可行的xml与json么？我不管转义还是没转义都无法发送成功
> > 另外[CQ:xml data=xxx]这个地方的[]需要转义么？
> > ![image](https://user-images.githubusercontent.com/30934916/90105674-e241d280-dd78-11ea-898a-43d930e966fd.png)
> 
> xml测试可以发送，json我用kotlin代码都发不出去。。。

xml代码请问能发我一份可行的么？
（至少目前没有被屏蔽的）

我[CQ:json data=xxx]不行

**Comment by PeratX** [comment]
> > > > > 我也是转了义以后发送不报错了，但是发送不显示。请问这个解决了吗
> > > > 
> > > > 
> > > > 这个还得向mirai汇报一下，现在发送的是正常的
> > > 
> > > 
> > > 能给我两个可行的xml与json么？我不管转义还是没转义都无法发送成功
> > > 另外[CQ:xml data=xxx]这个地方的[]需要转义么？
> > > ![image](https://user-images.githubusercontent.com/30934916/90105674-e241d280-dd78-11ea-898a-43d930e966fd.png)
> > 
> > 
> > xml测试可以发送，json我用kotlin代码都发不出去。。。
> 
> xml代码请问能发我一份可行的么？
> （至少目前没有被屏蔽的）
> 
> 我[CQ:json data=xxx]不行

```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="[回执消息]" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>]，索引：140 14:51:24 [ERROR] [MiraiNative] CQ消息解析失败：[CQ:xml,data=<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="107" templateID="1" action="viewReceiptMessage" brief="[回执消息]" m_resid="x0DwAEdLtzd2WJ15N2KHqOgjsp6eHn9TKKypawugshhvbhAju3TdnXtbrK7gDjhI" m_fileName="6688764403224599306" sourceMsgId="0" url="" flag="3" adverSign="0" multiMsgFlag="0"><item layout="29"><type>1</type></item><source name="" icon="" action="" appid="-1" /></msg>
```
这个转义之后测试可以发送

**Comment by m839336369** [comment]
感谢

**Comment by m839336369** [comment]
![image](https://user-images.githubusercontent.com/30934916/90112067-1a99de80-dd82-11ea-8530-56d72705e6f3.png)
![image](https://user-images.githubusercontent.com/30934916/90112157-37361680-dd82-11ea-8420-2b1723e8200f.png)
![image](https://user-images.githubusercontent.com/30934916/90112207-45843280-dd82-11ea-9e7c-4c93bfd43680.png)
请问我这么转义有什么问题么？

**Comment by PeratX** [comment]
[CQ:[空格]xml
此处不能有空格

**Comment by m839336369** [comment]
> [CQ:[空格]xml
> 此处不能有空格
> [CQ:xml,data=xxxxx]
> 符号前后不能有空格
> 
> ```
> GeneralControl.CQApi.SendPrivateMessage(frompersonal, "[CQ:xml,data=" + escape(File.ReadAllText(@"D:\YuanMa\XianYu_XianZhan_CQ\Pack\TextFile1.txt")) + "]");
> private static string escape(string msg) { return msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;").Replace(",", "&#44;"); }
> ```

非常感谢，另外我又找一个原因，逗号不需要替换，替换了反而不能用了
msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;");
这样就可以了

**Comment by PeratX** [comment]
> > [CQ:[空格]xml
> > 此处不能有空格
> > [CQ:xml,data=xxxxx]
> > 符号前后不能有空格
> > ```
> > GeneralControl.CQApi.SendPrivateMessage(frompersonal, "[CQ:xml,data=" + escape(File.ReadAllText(@"D:\YuanMa\XianYu_XianZhan_CQ\Pack\TextFile1.txt")) + "]");
> > private static string escape(string msg) { return msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;").Replace(",", "&#44;"); }
> > ```
> 
> 非常感谢，另外我又找一个原因，逗号不需要替换，替换了反而不能用了
> msg.Replace("&", "&").Replace("[", "[").Replace("]", "]");
> 这样就可以了

你这个替换是替换整个消息的逗号了，只需要escape data里面的逗号就行

**Comment by m839336369** [comment]
> > > [CQ:[空格]xml
> > > 此处不能有空格
> > > [CQ:xml,data=xxxxx]
> > > 符号前后不能有空格
> > > ```
> > > GeneralControl.CQApi.SendPrivateMessage(frompersonal, "[CQ:xml,data=" + escape(File.ReadAllText(@"D:\YuanMa\XianYu_XianZhan_CQ\Pack\TextFile1.txt")) + "]");
> > > private static string escape(string msg) { return msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;").Replace(",", "&#44;"); }
> > > ```
> > 
> > 
> > 非常感谢，另外我又找一个原因，逗号不需要替换，替换了反而不能用了
> > msg.Replace("&", "&").Replace("[", "[").Replace("]", "]");
> > 这样就可以了
> 
> 你这个替换是替换整个消息的逗号了，只需要escape data里面的逗号就行

![image](https://user-images.githubusercontent.com/30934916/90113596-2c7c8100-dd84-11ea-967c-35271e208023.png)
蓝色部分是data部分，我用escape替换的应该是data部分的啊，替换以后就不行了（比心

**Comment by PeratX** [comment]
> > > > [CQ:[空格]xml
> > > > 此处不能有空格
> > > > [CQ:xml,data=xxxxx]
> > > > 符号前后不能有空格
> > > > ```
> > > > GeneralControl.CQApi.SendPrivateMessage(frompersonal, "[CQ:xml,data=" + escape(File.ReadAllText(@"D:\YuanMa\XianYu_XianZhan_CQ\Pack\TextFile1.txt")) + "]");
> > > > private static string escape(string msg) { return msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;").Replace(",", "&#44;"); }
> > > > ```
> > > 
> > > 
> > > 非常感谢，另外我又找一个原因，逗号不需要替换，替换了反而不能用了
> > > msg.Replace("&", "&").Replace("[", "[").Replace("]", "]");
> > > 这样就可以了
> > 
> > 
> > 你这个替换是替换整个消息的逗号了，只需要escape data里面的逗号就行
> 
> ![image](https://user-images.githubusercontent.com/30934916/90113596-2c7c8100-dd84-11ea-967c-35271e208023.png)
> 蓝色部分是data部分，我用escape替换的应该是data部分的啊，替换以后就不行了（比心

有可能，现行版本还没修复这个错误，下个版本就没问题了

**Comment by m839336369** [comment]
> > > > > [CQ:[空格]xml
> > > > > 此处不能有空格
> > > > > [CQ:xml,data=xxxxx]
> > > > > 符号前后不能有空格
> > > > > ```
> > > > > GeneralControl.CQApi.SendPrivateMessage(frompersonal, "[CQ:xml,data=" + escape(File.ReadAllText(@"D:\YuanMa\XianYu_XianZhan_CQ\Pack\TextFile1.txt")) + "]");
> > > > > private static string escape(string msg) { return msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;").Replace(",", "&#44;"); }
> > > > > ```
> > > > 
> > > > 
> > > > 非常感谢，另外我又找一个原因，逗号不需要替换，替换了反而不能用了
> > > > msg.Replace("&", "&").Replace("[", "[").Replace("]", "]");
> > > > 这样就可以了
> > > 
> > > 
> > > 你这个替换是替换整个消息的逗号了，只需要escape data里面的逗号就行
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/30934916/90113596-2c7c8100-dd84-11ea-967c-35271e208023.png)
> > 蓝色部分是data部分，我用escape替换的应该是data部分的啊，替换以后就不行了（比心
> 
> 有可能，现行版本还没修复这个错误，下个版本就没问题了

感谢+期待

**Comment by PeratX** [comment]
> > > > [CQ:[空格]xml
> > > > 此处不能有空格
> > > > [CQ:xml,data=xxxxx]
> > > > 符号前后不能有空格
> > > > ```
> > > > GeneralControl.CQApi.SendPrivateMessage(frompersonal, "[CQ:xml,data=" + escape(File.ReadAllText(@"D:\YuanMa\XianYu_XianZhan_CQ\Pack\TextFile1.txt")) + "]");
> > > > private static string escape(string msg) { return msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;").Replace(",", "&#44;"); }
> > > > ```
> > > 
> > > 
> > > 非常感谢，另外我又找一个原因，逗号不需要替换，替换了反而不能用了
> > > msg.Replace("&", "&").Replace("[", "[").Replace("]", "]");
> > > 这样就可以了
> > 
> > 
> > 你这个替换是替换整个消息的逗号了，只需要escape data里面的逗号就行
> 
> ![image](https://user-images.githubusercontent.com/30934916/90113596-2c7c8100-dd84-11ea-967c-35271e208023.png)
> 蓝色部分是data部分，我用escape替换的应该是data部分的啊，替换以后就不行了（比心

顺便求个star ❤️

**Comment by m839336369** [comment]
> > > > > [CQ:[空格]xml
> > > > > 此处不能有空格
> > > > > [CQ:xml,data=xxxxx]
> > > > > 符号前后不能有空格
> > > > > ```
> > > > > GeneralControl.CQApi.SendPrivateMessage(frompersonal, "[CQ:xml,data=" + escape(File.ReadAllText(@"D:\YuanMa\XianYu_XianZhan_CQ\Pack\TextFile1.txt")) + "]");
> > > > > private static string escape(string msg) { return msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;").Replace(",", "&#44;"); }
> > > > > ```
> > > > 
> > > > 
> > > > 非常感谢，另外我又找一个原因，逗号不需要替换，替换了反而不能用了
> > > > msg.Replace("&", "&").Replace("[", "[").Replace("]", "]");
> > > > 这样就可以了
> > > 
> > > 
> > > 你这个替换是替换整个消息的逗号了，只需要escape data里面的逗号就行
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/30934916/90113596-2c7c8100-dd84-11ea-967c-35271e208023.png)
> > 蓝色部分是data部分，我用escape替换的应该是data部分的啊，替换以后就不行了（比心
> 
> 顺便求个star ❤️

哈哈哈
我刚刚试了试json，发现json需要逗号转义，但是转义以后虽然可以识别，但是无法显示消息
![J4}(A88O ~QMVXGK0FC)AQW](https://user-images.githubusercontent.com/30934916/90119750-8aad6200-dd8c-11ea-9dee-639b5af92686.png)

**Comment by PeratX** [comment]
> > > > > > [CQ:[空格]xml
> > > > > > 此处不能有空格
> > > > > > [CQ:xml,data=xxxxx]
> > > > > > 符号前后不能有空格
> > > > > > ```
> > > > > > GeneralControl.CQApi.SendPrivateMessage(frompersonal, "[CQ:xml,data=" + escape(File.ReadAllText(@"D:\YuanMa\XianYu_XianZhan_CQ\Pack\TextFile1.txt")) + "]");
> > > > > > private static string escape(string msg) { return msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;").Replace(",", "&#44;"); }
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 非常感谢，另外我又找一个原因，逗号不需要替换，替换了反而不能用了
> > > > > msg.Replace("&", "&").Replace("[", "[").Replace("]", "]");
> > > > > 这样就可以了
> > > > 
> > > > 
> > > > 你这个替换是替换整个消息的逗号了，只需要escape data里面的逗号就行
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/30934916/90113596-2c7c8100-dd84-11ea-967c-35271e208023.png)
> > > 蓝色部分是data部分，我用escape替换的应该是data部分的啊，替换以后就不行了（比心
> > 
> > 
> > 顺便求个star ❤️
> 
> 哈哈哈
> 我刚刚试了试json，发现json需要逗号转义，但是转义以后虽然可以识别，但是无法显示消息
> ![J4}(A88O ~QMVXGK0FC)AQW](https://user-images.githubusercontent.com/30934916/90119750-8aad6200-dd8c-11ea-9dee-639b5af92686.png)

确实不行，我自己也发不出去，等mirai更新吧

**Comment by PeratX** [comment]
> > > > > > [CQ:[空格]xml
> > > > > > 此处不能有空格
> > > > > > [CQ:xml,data=xxxxx]
> > > > > > 符号前后不能有空格
> > > > > > ```
> > > > > > GeneralControl.CQApi.SendPrivateMessage(frompersonal, "[CQ:xml,data=" + escape(File.ReadAllText(@"D:\YuanMa\XianYu_XianZhan_CQ\Pack\TextFile1.txt")) + "]");
> > > > > > private static string escape(string msg) { return msg.Replace("&", "&amp;").Replace("[", "&#91;").Replace("]", "&#93;").Replace(",", "&#44;"); }
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 非常感谢，另外我又找一个原因，逗号不需要替换，替换了反而不能用了
> > > > > msg.Replace("&", "&").Replace("[", "[").Replace("]", "]");
> > > > > 这样就可以了
> > > > 
> > > > 
> > > > 你这个替换是替换整个消息的逗号了，只需要escape data里面的逗号就行
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/30934916/90113596-2c7c8100-dd84-11ea-967c-35271e208023.png)
> > > 蓝色部分是data部分，我用escape替换的应该是data部分的啊，替换以后就不行了（比心
> > 
> > 
> > 顺便求个star ❤️
> 
> 哈哈哈
> 我刚刚试了试json，发现json需要逗号转义，但是转义以后虽然可以识别，但是无法显示消息
> ![J4}(A88O ~QMVXGK0FC)AQW](https://user-images.githubusercontent.com/30934916/90119750-8aad6200-dd8c-11ea-9dee-639b5af92686.png)

新添加了个类型`LightApp`的发送，请尝试用`[CQ:app,data=xxx]`发送JSON消息
