### ISSUE TITLE
Native上线监听器错误

### ISSUE THREAD

**Issue by GiGaFotress** [iTXTech/mirai-native#120]
**描述这个Bug**
Native插件启动后无法监听到上线事件，新起一套MCL排除所有插件和附属运行库进行部署，故障依旧
**复现步骤**
重新下载一份MCL1.03，安装mirainative，故障依旧
**期望的行为**
mirai-native正常启动

**截图和日志**
https://i.loli.net/2021/01/11/GwI5TSp8Zj7gcil.png
https://i.loli.net/2021/01/11/wxv75yIXPnQmMRV.png

**运行环境**
 - 操作系统：win10 1607 LTSB
 - `mirai core` 版本：2.0-RC-dev8
 - `mirai console` 版本：2.0-RC-dev1
 - `mirai native` 版本：1.9.6
 - `Java` 运行时版本：11.09
**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by GiGaFotress** [comment]
整体降级到M2版本正常，考虑双方兼容问题

**Comment by clhaaaa** [comment]
2.0-M2 -> 2.0-RC 有部分二进制不兼容，只能等作者更新了。
顺便一提，2.0-M2在我这边经常出现内存泄漏，等native更新等的我好急啊！

**Comment by GiGaFotress** [comment]
> 2.0-M2 -> 2.0-RC 有部分二进制不兼容，只能等作者更新了。
> 顺便一提，2.0-M2在我这边经常出现内存泄漏，等native更新等的我好急啊！

M2的dev兼容性也有问题，部分插件起不来，我直接关了机器人等更新

**Comment by PeratX** [comment]
2.0-RC的更新马上就来，同时会加入mirai新版本特性支持

**Comment by dragon0629** [comment]
新特性貌似支持发小视频文件了，GOCQHTTP已经实现了CQ码

**Comment by PeratX** [comment]
> 新特性貌似支持发小视频文件了，GOCQHTTP已经实现了CQ码

mirai暂未支持

**Comment by PeratX** [comment]
已修复，见`2.0.0-beta.1`
