### ISSUE TITLE
无法正常接收信息

### ISSUE THREAD

**Issue by mengshouer** [iTXTech/mirai-native#122]
**描述这个Bug**
插件中如果存在CQHTTP的情况下，并且配置文件的posturl填写访问出错时，会导致所有插件接受异常，其他功能均正常。表现为1：延迟几十秒或好几分钟才收到消息；2：甚至收不到消息。

**复现步骤**
安装个CQHTTP插件并填写了无法正常访问的posturl

**期望的行为**
在服务端出现无法正常提供服务时，其他部件正常

**截图和日志**
https://i.loli.net/2021/01/19/UAOLzZtQqisPvh8.png

**运行环境**
 - 操作系统：Windows Server 2019
 - `mirai core` 版本：2.0.0/1.3.3
 - `mirai console` 版本：2.0.0/1.1.0
 - `mirai native` 版本：2.0.0-beta/1.9.4
 - `Java` 运行时版本：11.0.9 x86

**更多信息**
"post_url": "http://tataru.aoba.vip/api/cq_http_api.php?key=123123"

**Comment by PeratX** [comment]
您已经知晓这是因为插件配置错误导致的。

mirai native在处理事件时默认有双倍于逻辑CPU数量的线程，当线程全部被阻塞，就会发生上述情况。

**Comment by mengshouer** [comment]
还有种情况，比如说配置文件正常，服务端正常提供服务，但是由于某些原因服务端挂了，暂时无法提供服务。这种情况也会导致其他部件无法使用，解决方法只能先删除url，服务正常再添加？但是如果服务端时不时挂一会的话，这种情况下手动修改文件又不可取。(服务为别人提供的，自己不可控
