### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by 1321008977** [iTXTech/mirai-native#124]
描述 : Native启动错误，如图所示，启动报错

复现错误 : 启动时

期望的行为 : 正常启动

截图 : 
![image](https://user-images.githubusercontent.com/63497854/106419908-812bc980-6494-11eb-8833-51f9cba15f58.png)

log: 不知道保存在哪

 - 操作系统：windows server 2008
 - `mirai core` 版本：2.2.2
 - `mirai console` 版本：2.2.2
 - `mirai native` 版本：1.9.6
 - `Java` 运行时版本：11.0.9.1 x86

**Comment by z594024037** [comment]
要不你去试试2.0.0-beta1版本的native呗

**Comment by dragon0629** [comment]
这不算BUG吧

**Comment by PeratX** [comment]
运行
`.\mcl --update-package org.itxtech:mirai-native --channel beta`
尝试再次启动，将自动更新到`2.0.0-beta.1`
