### ISSUE TITLE
发送不存在的URL图片时，整个消息都会被吞掉

### ISSUE THREAD

**Issue by Amazefcc233** [iTXTech/mirai-native#125]
**描述这个Bug**
发送不存在的URL图片时，整个消息都会被吞掉
（目前发现仅url图片会这样，发送本地图片不会有吞掉整条消息的问题）

**复现步骤**
- 机器人发送一张不存在的url图片
- 报java.io.FileNotFoundException，并不发送消息

**期望的行为**
去除无效的图片，发送文字及其他有效的url图片
大概就是这样：![Snipaste_2021-02-01_16-04-17.png](https://i.loli.net/2021/02/01/TUIgbCLQ7dmDfyv.png) 
（ https://i.loli.net/2021/02/01/TUIgbCLQ7dmDfyv.png ）
或返回一个负数值

**截图和日志**
演示代码：![Snipaste_2021-02-01_15-36-20.png](https://i.loli.net/2021/02/01/iowM4FlnHJqBNUy.png)
（ https://i.loli.net/2021/02/01/iowM4FlnHJqBNUy.png ）
实际收到内容：![Snipaste_2021-02-01_16-00-16.png](https://i.loli.net/2021/02/01/Tth4GJNsqWAZod5.png)
（ https://i.loli.net/2021/02/01/Tth4GJNsqWAZod5.png ）
后台日志：![IMG_1945_20210201-160126_.JPEG](https://i.loli.net/2021/02/01/iqhNIYUjJCl4B6Q.jpg)
（ https://i.loli.net/2021/02/01/iqhNIYUjJCl4B6Q.jpg ）

**运行环境**
 - 操作系统：Windows Server 2012 R2
 - `mirai core` 版本：2.2.2
 - `mirai console` 版本：2.2.2
 - `mirai native` 版本：2.0.0-beta.1
 - `Java` 运行时版本：11.0.9.1 x86

**Comment by PeratX** [comment]
为什么不确保自己发送的图片是有效的呢？发送无效的图片确实应该被视为无效的消息并抛出异常。

**Comment by Amazefcc233** [comment]
有时候会有类似于某些图床因为空间限制或者自动删除等策略抹除一些图片而不告知上传者的情况存在，没法确保自己发送的图片是有效的，而不发送剩余有效内容的话再加上没法得知消息是否发送成功，如果不看后台日志无法知道是mirai或自己写的插件故障还是只是有一张无效的url图片在消息里面

**Comment by PeratX** [comment]
发送前自行验证url就可以确保有效了，并且这样能提升用户体验。

**Comment by Amazefcc233** [comment]
懂了，感谢大佬帮助
