### ISSUE TITLE
BOT受邀入群时事件未能触发

### ISSUE THREAD

**Issue by zxin8580** [iTXTech/mirai-native#126]
**描述这个Bug**
BOT受邀>100人的群时不触发BotJoinGroupEvent.Invite(_eventSystem_GroupMemberIncrease)事件

**复现步骤**
邀请BOT到任意百人以上大群

**期望的行为**
希望可以像被拉入少于30(?不确定这个界限是多少人)人那样可以触发事件, 以实现插件自动同意入群的功能

**截图和日志**

**--- 被拉入人数较少的群时可触发事件**
`2021-02-03 21:07:30 V/Bot.3170######: Event: BotJoinGroupEvent.Invite(invitor=NormalMember(916857###))
2021-02-03 21:07:30 W/MiraiNative: [TinyStar GroupMemberIncrease] subtype: 2, sendTime: 1744914453, fromGroup: 915950917, fromQQ: 916857###, beingOperateQQ: 3170######`

**--- 被拉入人数较多的群时可接收到xml格式的邀请消息，不触发事件**
`2021-02-03 21:07:50 V/Bot.3170######: 攻城叔 ଲ(916857###) -> [mirai:service:128,<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><msg serviceID="128" templateID="12345" action="native" brief="[链接]邀请你加入群聊" sourceMsgId="0" url=""><item layout="2"><picture cover=""/><title>邀请你加入群聊</title><summary /></item><data groupcode="1014828867" groupname="香肠战队" msgseq="1612357672114518" msgtype="2"/></msg>]`

- 操作系统：Windows 10 20H2 19042.746
 - `mcl` 版本：1.0.4-b4213ea
 - `protocol`: ANDROID_PHONE
 - `mirai core` 版本：2.3.2
 - `mirai console` 版本：2.3.2
 - `mirai native` 版本：2.0.0-beta.1
 - `Java` 运行时版本：11.0.10 x86

**Comment by PeratX** [comment]
xml消息本身是一条消息并不会触发事件。
如果需要进一步支持，请向mirai反馈，mirainative只负责转发事件而不负责触发事件。
