### ISSUE TITLE
将获取用户等级功能加入Mirai Native APIs的请求

### ISSUE THREAD

**Issue by zxin8580** [iTXTech/mirai-native#128]
**特性描述**
[https://github.com/mamoe/mirai/issues/967#issue-801216225](url)

请问mirai native能否考虑将此功能列入Mirai Native APIs供调用

**Comment by PeratX** [comment]
好的，相关功能可能会在2.0.0的beta的某个版本中加入，请留意commit和wiki更新

**Comment by PeratX** [comment]
目前个人开发重心在 [mcl-installer](https://github.com/iTXTech/mcl-installer) ，待该项目完善后（一两天），才会转来开发`mirai native`

**Comment by zxin8580** [comment]
哇，别说一两天，一两周也愿意等(｡・`ω´･)

**Comment by PeratX** [comment]
`getStrangerInfo`已更新，编码如下，修改相关代码就可以获取多出来的`qLevel`，`email`和`sign`了

```kotlin
               writeLong(account)
                writeString(profile.nickname)
                writeInt(profile.sex.ordinal)
                writeInt(profile.age)
                writeInt(profile.qLevel)
                writeString(profile.email)
                writeString(profile.sign)
```

**Comment by zxin8580** [comment]
感谢大佬~

**Comment by zxin8580** [comment]
https://github.com/iTXTech/mirai-native/blob/e521e09a7614f98f462d1d9c3d3ed85ed5817e7d/src/main/kotlin/org/itxtech/mirainative/bridge/MiraiBridge.kt#L428

大佬，我昨天测试了一下member.queryProfile()好像会对getGroupMemberList()的执行效率有挺大影响，尝试注释掉并返回sex,age=0后效率恢复正常了

**Comment by PeratX** [comment]
是的，mirai默认没有缓存这些数据，所以全部查询的话确实会很慢
