### ISSUE TITLE
请求关于多BOT登录环境下判断消息来源的可行性

### ISSUE THREAD

**Issue by zxin8580** [iTXTech/mirai-native#129]
**特性描述**
才疏学浅....不知能否为每个登录的bot都load一份插件，或者根据接收到的消息ID识别收到消息的来源bot，在发送时导向到对应的bot发出是否可行... 我了解到因为原先CQ没有对多Q环境做考虑和兼容，在具体实现上能考虑到的也只是表象，默默的问一下...

**Comment by PeratX** [comment]
不考虑实现，需要多个QQ请启动多个mirai实例。
