### ISSUE TITLE
私聊发送图片数量超限后bot无法正常发出消息

### ISSUE THREAD

**Issue by Pika-Lee** [iTXTech/mirai-native#141]
**描述这个Bug**
如题，QQ私聊每日最多可发送2000张图片。超过此限制后，bot将无法发送带图片的消息内容。

**复现步骤**
1.让Bot一天内私聊发送2000张图片
2.下一条带图片的私聊消息，bot无法正常发出

**期望的行为**
建议遇到此情况后，能够让bot正常发出不带图片的文字消息，而不是无法发出整条消息。

**截图和日志**
![QQ截图20210603172527](https://user-images.githubusercontent.com/23114990/120626788-97bf4d00-c495-11eb-82e6-aac573dfc6d2.png)

**运行环境**
 - 操作系统：Windows Server 2016
 - `mirai core` 版本：2.2.2
 - `mirai console` 版本：2.2.2
 - `mirai native` 版本：2.0.0-beta1
 - `Java` 运行时版本：11.0.7 x86

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
mirai的问题，我看到您已经反馈给mirai了，与mirai native无关。

**Comment by Pika-Lee** [comment]
你好，mirai那边反馈说是需要native加一个exception的处理来解决这个问题，ERROR也定位在了native这里，所以还得麻烦大佬再处理一下~
![QQ截图20210606183048](https://user-images.githubusercontent.com/23114990/120921309-b0c63900-c6f5-11eb-821c-b90a1ac12124.png)
