### ISSUE TITLE
还是仅支持32位的jre吗，mirai最新的版本要java11了，没有32位的

### ISSUE THREAD

**Issue by Rrrrrren** [iTXTech/mirai-native#143]
rt

**Comment by 502milk** [comment]
> rt

adoptopenjdk了解下
[https://adoptopenjdk.net/](url)

**Comment by Rrrrrren** [comment]
> > rt
> 
> adoptopenjdk了解下
> [打开链接](https://adoptopenjdk.net/)

emmm，该怎么用

**Comment by 502milk** [comment]
> > > rt
> > 
> > adoptopenjdk了解下
> > [打开链接](https://adoptopenjdk.net/)
> 
> emmm，该怎么用

直接打开链接选你想要的版本就行了

**Comment by LookStars** [comment]
![image](https://user-images.githubusercontent.com/79433682/142725333-f3bf6a27-494c-43ba-a8d0-39664a1c6cd3.png)
真的找不到32位的 开始怀疑自己了....

**Comment by buger404** [comment]
建议将此issue置顶，或者写入readme。
