### ISSUE TITLE
在最新版本的mirai和mirai-native中，新成员入群申请触发的时候，会出现崩溃的情况。

### ISSUE THREAD

**Issue by SmileZXLee** [iTXTech/mirai-native#145]
**描述这个Bug**
清晰准确地表述这个Bug。
在最新版本的mirai和mirai-native中，新成员入群申请触发的时候，会出现崩溃的情况。
**复现步骤**
收到新成员入群申请的时候基本都会出现。
**期望的行为**
不出现崩溃的情况。

**截图和日志**
[hs_err_pid3820.log](https://github.com/iTXTech/mirai-native/files/7111154/hs_err_pid3820.log)

**运行环境**
 - 操作系统：Windows Server 2012R2
 - `mirai core` 版本：2.0.7
 - `mirai console` 版本：2.0.7
 - `mirai native` 版本：2.0.0-beta.1
 - `Java` 运行时版本：11.0.11

**更多信息**
插件只有一个，插件收到入群申请事件内部打印未触发，插件是基于Native.SDK开发的。
麻烦大佬了，感谢~

**Comment by SmileZXLee** [comment]
可能是账号问题，换个账号又正常了。

**Comment by PeratX** [comment]
处理事件的时候clr运行时崩溃了，考虑是插件兼容性问题，可以用VS附加调试器到java进程上进行调试
