### ISSUE TITLE
调用酷q移除群成员接口时报错

### ISSUE THREAD

**Issue by SmileZXLee** [iTXTech/mirai-native#146]
**描述这个Bug**
调用酷q移除群成员接口时报错

**复现步骤**
调用酷q移除群成员接口时报错，必定会出现，直接传群id和qq号也报错。 旧版本`mirai-native(1.8.2)`中可以正常移除群成员.
**期望的行为**
无
**截图和日志**
<img width="657" alt="image" src="https://user-images.githubusercontent.com/29226317/132133117-fb112d2e-ae56-4942-863a-5ecdd031cbee.png">

**运行环境**
-操作系统：Windows Server 2012R2
- mirai core 版本：2.0.7
- mirai console 版本：2.0.7
- mirai native 版本：2.0.0-beta.1
- Java 运行时版本：11.0.11

**Comment by PeratX** [comment]
这个已经修复，等待发布新版本

**Comment by SmileZXLee** [comment]
> 这个已经修复，等待发布新版本

好的，感谢！
