### ISSUE TITLE
撤回消息失败，消息一发出来马上撤回可以，过1分钟左右撤回失败

### ISSUE THREAD

**Issue by SmileZXLee** [iTXTech/mirai-native#149]
**描述这个Bug**
撤回消息失败，消息一发出来马上撤回可以，过1分钟左右撤回失败

**复现步骤**
发送一条消息，1分钟内可以正常撤回，1分钟后撤回失败。也有出现1分钟内就撤回失败的，感觉是随机出现，测试了图片、文字、表情，未找到很明确的规律。使用旧版正常。
**期望的行为**
可以正常地撤回消息。

**截图和日志**
无任何报错

**运行环境**
-操作系统：Windows Server 2012R2

mirai core 版本：2.7.1-dev-1
mirai console 版本：2.7.1-dev-1
mirai native 版本：2.0.0-beta.1
Java 运行时版本：11.0.11

**Comment by PeratX** [comment]
可以升级到最新mirai尝试，这个问题请反馈给mirai
