### ISSUE TITLE
可否添加一个设置托盘开启或禁用的配置

### ISSUE THREAD

**Issue by diocat** [iTXTech/mirai-native#15]
wine下会因为没有图形界面导致jwt报错无法启动插件

**Comment by PeratX** [comment]
将会加入自动检测

**Comment by PeratX** [comment]
目前在创建托盘菜单时会判断是否支持，只有支持才会创建，请提供完整的报错信息

**Comment by diocat** [comment]
![QQ截图20200805203505](https://user-images.githubusercontent.com/16731922/89413346-4a7e2c00-d75b-11ea-9292-6317fa811d32.png)

**Comment by PeratX** [comment]
创建的时候 我用try-catch包起来就行了

**Comment by diocat** [comment]
src/main/kotlin/org/itxtech/mirainative/MiraiNative.kt:89  在这里插入try catch，因为不止只有tray会报错

`        try {
            Tray.create()
            FloatingWindow.create()
        } catch (e: Throwable) {
            MiraiNative.logger.error(e)
        }`
