### ISSUE TITLE
如何安装windows 32位 JRE

### ISSUE THREAD

**Issue by LookStars** [iTXTech/mirai-native#153]
我查阅了很多资料，但是依旧无法正确的安装32位java或者是说我安装了但是我无法正常的去配置他们，希望有人可以指导我一下

**Comment by Kloping** [comment]
+1  11+

**Comment by 502milk** [comment]
[#143](https://github.com/iTXTech/mirai-native/issues/143)

**Comment by Kloping** [comment]
> [#143](https://github.com/iTXTech/mirai-native/issues/143)

行,感谢

**Comment by LookStars** [comment]
> [#143](https://github.com/iTXTech/mirai-native/issues/143)

> [#143](https://github.com/iTXTech/mirai-native/issues/143)

谢谢

**Comment by LookStars** [comment]
![image](https://user-images.githubusercontent.com/79433682/142468786-7bbf4eef-7a10-43fa-829a-75ed16f9e4fa.png)
我安装了OpenJDK，但是依旧不能运行，我怀疑我安装错了，安装成了64位的java，请问一下我是不是安装错了

**Comment by 502milk** [comment]
> ![image](https://user-images.githubusercontent.com/79433682/142468786-7bbf4eef-7a10-43fa-829a-75ed16f9e4fa.png)
> 我安装了OpenJDK，但是依旧不能运行，我怀疑我安装错了，安装成了64位的java，请问一下我是不是安装错了

肯定错了啊

**Comment by LookStars** [comment]
![image](https://user-images.githubusercontent.com/79433682/142725353-443f5d59-921b-4c41-acd2-c582becc4be5.png)
真的找不到32位的，有没有具体链接和操作的教程呀，开始怀疑自己了

**Comment by Kloping** [comment]
![image](https://user-images.githubusercontent.com/87743020/142725432-8dc54669-d05a-4731-9a74-919f4d240526.png)

**Comment by LookStars** [comment]
> ![图片](https://user-images.githubusercontent.com/87743020/142725432-8dc54669-d05a-4731-9a74-919f4d240526.png)

我找到了我自己的安装目录，也有该版本的jre，也就是说目前我是安装好了jre的，那么...请问我应该如何使用此版本的java来启动我的mirai console loader

**Comment by LookStars** [comment]
> ![图片](https://user-images.githubusercontent.com/87743020/142725432-8dc54669-d05a-4731-9a74-919f4d240526.png)

谢谢回复

**Comment by 502milk** [comment]
> > ![图片](https://user-images.githubusercontent.com/87743020/142725432-8dc54669-d05a-4731-9a74-919f4d240526.png)
> 
> 谢谢回复

MCL在启动时就可以选择是否使用32位java并自动下载

**Comment by 502milk** [comment]
> ![image](https://user-images.githubusercontent.com/79433682/142725353-443f5d59-921b-4c41-acd2-c582becc4be5.png)
> 真的找不到32位的，有没有具体链接和操作的教程呀，开始怀疑自己了

选择其他平台即可

**Comment by LookStars** [comment]
> > ![image](https://user-images.githubusercontent.com/79433682/142725353-443f5d59-921b-4c41-acd2-c582becc4be5.png)
> > 真的找不到32位的，有没有具体链接和操作的教程呀，开始怀疑自己了
> 
> 选择其他平台即可

谢谢回复 我已经解决了
