### ISSUE TITLE
2.13RC 似乎无法加载插件了

### ISSUE THREAD

**Issue by dragon0629** [iTXTech/mirai-native#166]
2022-10-24 19:42:09 I/main: mirai-console started successfully.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x73c8fd6d, pid=11808, tid=0x00001924
#
# JRE version: OpenJDK Runtime Environment (8.0_252-b09) (build 1.8.0_252-b09)
# Java VM: OpenJDK Client VM (25.252-b09 mixed mode windows-x86 )
# Problematic frame:
# V  [jvm.dll+0xbfd6d]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\MIRAI_2.13.1\hs_err_pid11808.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.j
[hs_err_pid11808.log](https://github.com/iTXTech/mirai-native/files/9851349/hs_err_pid11808.log)
sp
#
请按任意键继续. . .

囧rz[](url)

报错日志传了一个,emmm

**Comment by wpcwzy** [comment]
Same problem, need help. thx
