### ISSUE TITLE
登陆了多个bot时 所有发送信息全部会通过第一个bot发送出去

### ISSUE THREAD

**Issue by yp05327** [iTXTech/mirai-native#17]
现象：
登陆了多个bot时 所有发送信息全部会通过第一个登陆的bot发送出去

原先在酷q+cqhttp的环境下是可以多个酷q连接到同一个后台，
处理完毕后，再将返回消息发送给发送请求的酷q

不太清楚是不是这边的问题，想询问一下

**Comment by PeratX** [comment]
只支持单bot
