### ISSUE TITLE
更新mirai-console版本至2.13.2之后 启用插件时报错

### ISSUE THREAD

**Issue by Hellobaka** [iTXTech/mirai-native#172]
**描述这个Bug**
更新mirai-console版本至2.13.2之后 启用插件时报错

**复现步骤**
1. 启动mcl
2. 启用插件时报错

**期望的行为**
正常加载

**截图和日志**
```
2022-12-21 16:18:27 I/Bot.30*****057: Login successful.
2022-12-21 16:18:27 V/Bot.30*****057: Event: BotOnlineEvent(bot=Bot(30*****057))
2022-12-21 16:18:27 I/MiraiNative: Mirai Native 正启用所有插件。
2022-12-21 16:18:27 I/Bot.30*****057: Bot login successful.
2022-12-21 16:18:27 I/main: mirai-console started successfully.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x7ade67b6, pid=33012, tid=44288
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.8+10) (build 11.0.8+10)
# Java VM: OpenJDK Client VM AdoptOpenJDK (11.0.8+10, mixed mode, serial gc, windows-x86)
# Problematic frame:
# V  [jvm.dll+0x867b6]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\QQBot\mirai\hs_err_pid33012.log
> #
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#

```

**运行环境**
 - 操作系统：Windows11 22H2
 - `mirai core` 版本：2.13.2
 - `mirai console` 版本：2.13.2
 - `mirai native` 版本：2.0.1
 - `Java` 运行时版本：11.0.8 x86

**更多信息**
完整日志见附件
[hs_err_pid43952.log](https://github.com/iTXTech/mirai-native/files/10275840/hs_err_pid43952.log)

**Comment by cssxsh** [comment]
请给出具体安装了什么 酷Q插件 
不然无法复现

**Comment by 502milk** [comment]
同样问题+1（已经换过java版本无解
[bilibili V2.6.0.zip](https://github.com/iTXTech/mirai-native/files/10283547/bilibili.V2.6.0.zip)
在不装酷Q插件的时候能正常跑 
只要载入酷Q插件必崩

**Comment by Hellobaka** [comment]
> 请给出具体安装了什么 酷Q插件 不然无法复现

任意插件均会导致报错 我提供一个样本插件以供研究
[cn.izoyo.manager.zip](https://github.com/iTXTech/mirai-native/files/10284821/cn.izoyo.manager.zip)

**Comment by cssxsh** [comment]
https://github.com/iTXTech/mirai-native/commit/0add0a2c55479e46436b85a53b87617f21efe803

原因大概是 这个更新中对 CQP 进行了重新编译，也许那次编译出了什么问题

https://github.com/iTXTech/mirai-native/issues/167#issuecomment-1304617220

可以试试看我之前编译的版本

**Comment by PeratX** [comment]
是不是因为我加了个upx壳的原因

**Comment by PeratX** [comment]
你用UPX unpack一下试试看

**Comment by Hellobaka** [comment]
脱壳之后尺寸变为111KB，不过依旧会报错呢

**Comment by dragon0629** [comment]
也遇到了，确实 2.13.2 加载酷q插件必挂
但回退2.13.0 一切正常

**Comment by zxin8580** [comment]
> 也遇到了，确实 2.13.2 加载酷q插件必挂 但回退2.13.0 一切正常

22年8月之前commit的版本可在2.13.2正常加载，先退回旧版试试

**Comment by dragon0629** [comment]
> 

?之前的版本不是2.13就不支持了嘛
