### ISSUE TITLE
当机器人收到入群申请并同意时，_eventSystem_GroupMemberIncrease事件不会触发

### ISSUE THREAD

**Issue by SmileZXLee** [iTXTech/mirai-native#19]
如果机器人没有自动同意入群申请，由管理员同意，会触发`_eventSystem_GroupMemberIncrease `

**Comment by PeratX** [comment]
应该是这样的，不知道CQ的逻辑是？

**Comment by SmileZXLee** [comment]
> 应该是这样的，不知道CQ的逻辑是？

酷Q的逻辑是只要有人加群成功都会触发(包含机器人被邀请进群)，目前有个功能是有人申请加群，机器人验证加群者的身份，比如加群者输入学号，我通过这个学号查到加群者的信息，就自动通过入群申请，并且在该申请者加群成功后，根据查询到的信息将他的名片改成入学年份-专业-昵称的格式。
如果机器人被邀请进群，我是有自动发一段话：“感谢邀请，发送xxx查看我会什么哦”~
所以希望不管什么情况只要有新成员进群都能触发`_eventSystem_GroupMemberIncrease`，允许插件自行决定要不要处理。
感谢大佬！

**Comment by PeratX** [comment]
目前的逻辑是，只有已经加入群了才会触发该事件。

**Comment by PeratX** [comment]
您的意思是，机器人同意邀请后也要触发该事件？

**Comment by SmileZXLee** [comment]
> 目前的逻辑是，只有已经加入群了才会触发该事件。
> 认证加群的事件和Bot被邀请入群是`_eventRequest_AddGroup`
`_eventRequest_AddGroup`收到加群请求时候才会触发，但是收到加群请求的时候无法修改群成员名片，因为此时这个成员还没进群，希望新成员成功进入群以后，可以都触发`_eventSystem_GroupMemberIncrease`事件。

**Comment by SmileZXLee** [comment]
> 您的意思是，机器人同意邀请后也要触发该事件？

机器人同意邀请后加入群，希望能触发`_eventSystem_GroupMemberIncrease`事件，并且希望机器人同意其他用户的加群申请后也能触发`_eventSystem_GroupMemberIncrease`。

**Comment by PeratX** [comment]
> > 您的意思是，机器人同意邀请后也要触发该事件？
> 
> 机器人同意邀请后加入群，希望能触发`_eventSystem_GroupMemberIncrease`事件，并且希望机器人同意其他用户的加群申请后也能触发`_eventSystem_GroupMemberIncrease`。

请提供以上两种情况的subType

**Comment by SmileZXLee** [comment]
> > > 您的意思是，机器人同意邀请后也要触发该事件？
> > 
> > 
> > 机器人同意邀请后加入群，希望能触发`_eventSystem_GroupMemberIncrease`事件，并且希望机器人同意其他用户的加群申请后也能触发`_eventSystem_GroupMemberIncrease`。
> 
> 请提供以上两种情况的subType

麻烦大佬了。
我使用的是Native.Sdk
```csharp
public enum CQGroupMemberIncreaseType
{
	/// <summary>
	/// 同意入群
	/// </summary>
	Pass = 1,
	/// <summary>
	/// 邀请入群
	/// </summary>
	Invite = 2
}
```
在`_eventSystem_GroupMemberIncrease`事件中
```csharp
if (e.SubType == Native.Sdk.Cqp.Enum.CQGroupMemberIncreaseType.Invite){
	//这边可以判断是qq机器人自身被邀请进群还是其他qq被邀请进群
	e.CQLog.Debug("邀请进群", $"{e.FromQQ?.Id ?? -1} 邀请 {e.BeingOperateQQ?.Id ?? -1} 加入了群 {e.FromGroup?.Id ?? -1}.");
}
else{
	e.CQLog.Debug("自主进群", $"{e.FromQQ?.Id ?? -1}加入了群");
}
```

**Comment by PeratX** [comment]
已发布新版本，请测试

**Comment by SmileZXLee** [comment]
> 已发布新版本，请测试

完美解决，感谢！！

**Comment by yoonching** [comment]
似乎我跟您遇到了同样的情况，目前我按照这篇issue的指示更新了jar包。目前还在观察。
我也是做类似学号入群审批的，做的一个插件通过csv文件内预设的名单及检验字段，如果输入答案与检验字段符合，则根据一些规则生成群名片置给新进群QQ用户。
审批这块倒是很顺利，当走到**CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时)**这个易语言API时，报错。
贴一下日志，同时继续观察从1.8.1更新到1.8.4版本jar包后的情况。

 23:24:28 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgNew.Group
 23:24:28 [INFO] [BOT 715209226] Event: MemberJoinRequestEvent(bot=Bot(715******), eventId=1597332268741556, message=问 题：请输入十五位考生号\n答案：1034569***    fromId=1101328***, groupId=700******, groupName=某某新生群, fromNick=Still seven)
 23:24:28 [DEBUG] [MiraiNative] [加群自动审批本地版2020 用户输入答案] 1034569***    
 23:24:30 [DEBUG] [MiraiNative] [加群自动审批本地版2020 设置用户群名片为：] 20-某某学院-张三
 23:24:30 [ERROR] [MiraiNative]
 23:24:30 [ERROR] [MiraiNative] java.util.NoSuchElementException: member 1101328*** not found in group 700******
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:273)
        at org.itxtech.mirainative.bridge.MiraiBridge.setGroupCard(MiraiBridge.kt:159)
        at org.itxtech.mirainative.Bridge.setGroupCard(Bridge.kt:192)
        at org.itxtech.mirainative.Bridge.pEvRequestAddGroup(Native Method)
        at org.itxtech.mirainative.bridge.NativeBridge.eventRequestAddGroup(NativeBridge.kt:252)
        at org.itxtech.mirainative.manager.EventManager$registerEvents$8$1.invokeSuspend(EventManager.kt:134)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

 23:24:30 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgAction.Group
 23:24:30 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 23:24:30 [INFO] [NETWORK] Received unknown commandName: ProfileService.Pb.ReqSystemMsgAction.Group
 23:24:30 [INFO] [NETWORK] Send: OnlinePush.RespPush
 23:24:30 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 23:24:39 [INFO] [NETWORK] Send: OnlinePush.RespPush

**Comment by PeratX** [comment]
> 似乎我跟您遇到了同样的情况，目前我按照这篇issue的指示更新了jar包。目前还在观察。
> 我也是做类似学号入群审批的，做的一个插件通过csv文件内预设的名单及检验字段，如果输入答案与检验字段符合，则根据一些规则生成群名片置给新进群QQ用户。
> 审批这块倒是很顺利，当走到**CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时)**这个易语言API时，报错。
> 贴一下日志，同时继续观察从1.8.1更新到1.8.4版本jar包后的情况。
> 
> 23:24:28 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgNew.Group
> 23:24:28 [INFO] [BOT 715209226] Event: MemberJoinRequestEvent(bot=Bot(715******), eventId=1597332268741556, message=问 题：请输入十五位考生号\n答案：1034569*** fromId=1101328***, groupId=700******, groupName=某某新生群, fromNick=Still seven)
> 23:24:28 [DEBUG] [MiraiNative] [加群自动审批本地版2020 用户输入答案] 1034569***
> 23:24:30 [DEBUG] [MiraiNative] [加群自动审批本地版2020 设置用户群名片为：] 20-某某学院-张三
> 23:24:30 [ERROR] [MiraiNative]
> 23:24:30 [ERROR] [MiraiNative] java.util.NoSuchElementException: member 1101328*** not found in group 700******
> at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:273)
> at org.itxtech.mirainative.bridge.MiraiBridge.setGroupCard(MiraiBridge.kt:159)
> at org.itxtech.mirainative.Bridge.setGroupCard(Bridge.kt:192)
> at org.itxtech.mirainative.Bridge.pEvRequestAddGroup(Native Method)
> at org.itxtech.mirainative.bridge.NativeBridge.eventRequestAddGroup(NativeBridge.kt:252)
> at org.itxtech.mirainative.manager.EventManager$registerEvents$8$1.invokeSuspend(EventManager.kt:134)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> 
> 23:24:30 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgAction.Group
> 23:24:30 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
> 23:24:30 [INFO] [NETWORK] Received unknown commandName: ProfileService.Pb.ReqSystemMsgAction.Group
> 23:24:30 [INFO] [NETWORK] Send: OnlinePush.RespPush
> 23:24:30 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
> 23:24:39 [INFO] [NETWORK] Send: OnlinePush.RespPush

这个事件的时候，**成员还没有进入群**，可以用一个异步任务检查

**Comment by yoonching** [comment]
> > 似乎我跟您遇到了同样的情况，目前我按照这篇issue的指示更新了jar包。目前还在观察。
> > 我也是做类似学号入群审批的，做的一个插件通过csv文件内预设的名单及检验字段，如果输入答案与检验字段符合，则根据一些规则生成群名片置给新进群QQ用户。
> > 审批这块倒是很顺利，当走到**CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时)**这个易语言API时，报错。
> > 贴一下日志，同时继续观察从1.8.1更新到1.8.4版本jar包后的情况。
> > 23:24:28 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgNew.Group
> > 23:24:28 [INFO] [BOT 715209226] Event: MemberJoinRequestEvent(bot=Bot(715******), eventId=1597332268741556, message=问 题：请输入十五位考生号\n答案：1034569*** fromId=1101328***, groupId=700******, groupName=某某新生群, fromNick=Still seven)
> > 23:24:28 [DEBUG] [MiraiNative] [加群自动审批本地版2020 用户输入答案] 1034569***
> > 23:24:30 [DEBUG] [MiraiNative] [加群自动审批本地版2020 设置用户群名片为：] 20-某某学院-张三
> > 23:24:30 [ERROR] [MiraiNative]
> > 23:24:30 [ERROR] [MiraiNative] java.util.NoSuchElementException: member 1101328*** not found in group 700******
> > at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:273)
> > at org.itxtech.mirainative.bridge.MiraiBridge.setGroupCard(MiraiBridge.kt:159)
> > at org.itxtech.mirainative.Bridge.setGroupCard(Bridge.kt:192)
> > at org.itxtech.mirainative.Bridge.pEvRequestAddGroup(Native Method)
> > at org.itxtech.mirainative.bridge.NativeBridge.eventRequestAddGroup(NativeBridge.kt:252)
> > at org.itxtech.mirainative.manager.EventManager$registerEvents$8$1.invokeSuspend(EventManager.kt:134)
> > at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> > at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> > at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> > at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> > at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> > at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> > at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> > at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> > at java.lang.Thread.run(Thread.java:748)
> > 23:24:30 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgAction.Group
> > 23:24:30 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
> > 23:24:30 [INFO] [NETWORK] Received unknown commandName: ProfileService.Pb.ReqSystemMsgAction.Group
> > 23:24:30 [INFO] [NETWORK] Send: OnlinePush.RespPush
> > 23:24:30 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
> > 23:24:39 [INFO] [NETWORK] Send: OnlinePush.RespPush
> 
> 这个事件的时候，**成员还没有进入群**，可以用一个异步任务检查

收到，感谢您的回复。我会按照您的回复修改开发。

**Comment by PeratX** [comment]
> MemberJoinRequestEvent

能否给出详细逻辑？我帮你看看

**Comment by yoonching** [comment]
> > MemberJoinRequestEvent
> 
> 能否给出详细逻辑？我帮你看看

您好，久等了。我把与核心业务无关的一些验证剪掉，精简出了一些易语言代码。

首先是判断的subtype = 1（子类型，1/他人申请入群 2/自己(即登录号)受邀入群） 及判断了用户输入的key正确。
msg是用户输入的key。
接下来的核心逻辑如下：

                    CQ.置群添加请求 (responseFlag, #请求_群添加, #请求_通过)  ' 正确的key，通过请求
                    写配置项 (应用目录 ＋ “log_” ＋ 到文本 (fromGroup) ＋ “.ini”, 删首尾空 (文本区分_只取数字 (msg)), “验证时间”, 时间到文本 (取现行时间 (), 1))
                    写配置项 (应用目录 ＋ “log_” ＋ 到文本 (fromGroup) ＋ “.ini”, 删首尾空 (文本区分_只取数字 (msg)), “使用者”, 到文本 (fromQQ))
                    CQ.日志_调试 (“设置用户群名片为：”, 群名片临时)  **‘可以看到我贴出日志打印的DEBUG信息**
                    CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时) **'猜测是这里报错了**

**Comment by PeratX** [comment]
> > > MemberJoinRequestEvent
> > 
> > 
> > 能否给出详细逻辑？我帮你看看
> 
> 您好，久等了。我把与核心业务无关的一些验证剪掉，精简出了一些易语言代码。
> 
> 首先是判断的subtype = 1（子类型，1/他人申请入群 2/自己(即登录号)受邀入群） 及判断了用户输入的key正确。
> msg是用户输入的key。
> 接下来的核心逻辑如下：
> 
> ```
>                 CQ.置群添加请求 (responseFlag, #请求_群添加, #请求_通过)  ' 正确的key，通过请求
>                 写配置项 (应用目录 ＋ “log_” ＋ 到文本 (fromGroup) ＋ “.ini”, 删首尾空 (文本区分_只取数字 (msg)), “验证时间”, 时间到文本 (取现行时间 (), 1))
>                 写配置项 (应用目录 ＋ “log_” ＋ 到文本 (fromGroup) ＋ “.ini”, 删首尾空 (文本区分_只取数字 (msg)), “使用者”, 到文本 (fromQQ))
>                 CQ.日志_调试 (“设置用户群名片为：”, 群名片临时)  **‘可以看到我贴出日志打印的DEBUG信息**
>                 CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时) **'猜测是这里报错了**
> ```

应该在`_eventSystem_GroupMemberIncrease`事件中
` CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时)`

`Mirai Native`在成员成功加入后会调用该事件。

**Comment by yoonching** [comment]
> > > > MemberJoinRequestEvent
> > > 
> > > 
> > > 能否给出详细逻辑？我帮你看看
> > 
> > 
> > 您好，久等了。我把与核心业务无关的一些验证剪掉，精简出了一些易语言代码。
> > 首先是判断的subtype = 1（子类型，1/他人申请入群 2/自己(即登录号)受邀入群） 及判断了用户输入的key正确。
> > msg是用户输入的key。
> > 接下来的核心逻辑如下：
> > ```
> >                 CQ.置群添加请求 (responseFlag, #请求_群添加, #请求_通过)  ' 正确的key，通过请求
> >                 写配置项 (应用目录 ＋ “log_” ＋ 到文本 (fromGroup) ＋ “.ini”, 删首尾空 (文本区分_只取数字 (msg)), “验证时间”, 时间到文本 (取现行时间 (), 1))
> >                 写配置项 (应用目录 ＋ “log_” ＋ 到文本 (fromGroup) ＋ “.ini”, 删首尾空 (文本区分_只取数字 (msg)), “使用者”, 到文本 (fromQQ))
> >                 CQ.日志_调试 (“设置用户群名片为：”, 群名片临时)  **‘可以看到我贴出日志打印的DEBUG信息**
> >                 CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时) **'猜测是这里报错了**
> > ```
> 
> 应该在`_eventSystem_GroupMemberIncrease`事件中
> ` CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时)`
> 
> `Mirai Native`在成员成功加入后会调用该事件。

好的，非常感谢您的耐心指导！

**Comment by PeratX** [comment]
> > > > > MemberJoinRequestEvent
> > > > 
> > > > 
> > > > 能否给出详细逻辑？我帮你看看
> > > 
> > > 
> > > 您好，久等了。我把与核心业务无关的一些验证剪掉，精简出了一些易语言代码。
> > > 首先是判断的subtype = 1（子类型，1/他人申请入群 2/自己(即登录号)受邀入群） 及判断了用户输入的key正确。
> > > msg是用户输入的key。
> > > 接下来的核心逻辑如下：
> > > ```
> > >                 CQ.置群添加请求 (responseFlag, #请求_群添加, #请求_通过)  ' 正确的key，通过请求
> > >                 写配置项 (应用目录 ＋ “log_” ＋ 到文本 (fromGroup) ＋ “.ini”, 删首尾空 (文本区分_只取数字 (msg)), “验证时间”, 时间到文本 (取现行时间 (), 1))
> > >                 写配置项 (应用目录 ＋ “log_” ＋ 到文本 (fromGroup) ＋ “.ini”, 删首尾空 (文本区分_只取数字 (msg)), “使用者”, 到文本 (fromQQ))
> > >                 CQ.日志_调试 (“设置用户群名片为：”, 群名片临时)  **‘可以看到我贴出日志打印的DEBUG信息**
> > >                 CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时) **'猜测是这里报错了**
> > > ```
> > 
> > 
> > 应该在`_eventSystem_GroupMemberIncrease`事件中
> > ` CQ.置群成员名片 (fromGroup, fromQQ, 群名片临时)`
> > `Mirai Native`在成员成功加入后会调用该事件。
> 
> 好的，非常感谢您的耐心指导！

不客气呢 😄

**Comment by yoonching** [comment]
来反馈后续。

如您的指导，把设置群名片放到了_eventSystem_GroupMemberIncrease 事件中。**这次没有报错。**
但是从效果观察，群名片没有修改成功，日志来看，是有过修改名片操作的。所以我个人初步判定不再是mirai native的问题，可能是mirai方面的问题。

再翻看了mirai所有open和closed相关issue后，只翻到了这个，似乎也不是一回事。 https://github.com/mamoe/mirai/issues/211

因为mirai已经archived，决定暂时搁置问题了。作为给其他可能遇到问题的人的参考贴出以下信息。

以上，感谢您耐心的帮助。

事件内的易语言操作代码如下：
.版本 2

' 本子程序会在酷Q【线程】中被调用，请注意使用对象等需要初始化(CoInitialize,CoUninitialize)。
' 这里处理消息
' https://github.com/iTXTech/mirai-native/issues/19
.如果真 (subtype ＝ 1)
    群名片临时 ＝ 读配置项 (应用目录 ＋ “log_cardinfo_” ＋ 到文本 (fromGroup) ＋ “.ini”, 到文本 (beingOperateQQ), “名片文本”, “请修改群名片”)
    CQ.日志_调试 (“设置用户群名片为：”, 群名片临时)
    CQ.置群成员名片 (fromGroup, beingOperateQQ, 群名片临时)

日志如下。
18:03:53 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 18:03:53 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 18:03:53 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgNew.Group
 18:03:53 [INFO] [BOT 715209226] Event: MemberJoinRequestEvent(bot=Bot(7*****), eventId=1597399433447470, message=问 题：请输入*****\n答案：*****12, fromId=*****44, groupId=*****49, groupName=*****新生 群, fromNick=***炎)
 18:03:53 [DEBUG] [MiraiNative] [加群自动审批本地版2020 用户输入答案] *****12
 18:03:54 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgAction.Group
 18:03:54 [DEBUG] [MiraiNative] [加群自动审批本地版2020 设置用户群名片为：] 20-**学院-**希
 18:03:54 [INFO] [NETWORK] Send: friendlist.ModifyGroupCardReq
 18:03:54 [INFO] [NETWORK] Recv: TroopManagement.EditGroupNametag.Response
 18:03:54 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 18:03:54 [INFO] [NETWORK] Received unknown commandName: ProfileService.Pb.ReqSystemMsgAction.Group
 18:03:54 [INFO] [NETWORK] Send: OnlinePush.RespPush
 18:03:54 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 18:04:03 [INFO] [NETWORK] Send: OnlinePush.RespPush

**Comment by PeratX** [comment]
可以看到日志中
`Send: friendlist.ModifyGroupCardReq`
表明修改群名片的包已经发出了

**Comment by yoonching** [comment]
> 可以看到日志中
> `Send: friendlist.ModifyGroupCardReq`
> 表明修改群名片的包已经发出了

是的，因此我也没太搞清楚原因。“实名制入群”的功能需求已经达到，没能成功改名片，略有遗憾，影响不大。

**Comment by PeratX** [comment]
> > 可以看到日志中
> > `Send: friendlist.ModifyGroupCardReq`
> > 表明修改群名片的包已经发出了
> 
> 是的，因此我也没太搞清楚原因。“实名制入群”的功能需求已经达到，没能成功改名片，略有遗憾，影响不大。

待mirai开放issue了可以向上游反馈

**Comment by yoonching** [comment]
> > > 可以看到日志中
> > > `Send: friendlist.ModifyGroupCardReq`
> > > 表明修改群名片的包已经发出了
> > 
> > 
> > 是的，因此我也没太搞清楚原因。“实名制入群”的功能需求已经达到，没能成功改名片，略有遗憾，影响不大。
> 
> 待mirai开放issue了可以向上游反馈

好的，非常感谢您的帮助。

**Comment by SmileZXLee** [comment]
> > 可以看到日志中
> 
> > `Send: friendlist.ModifyGroupCardReq`
> 
> > 表明修改群名片的包已经发出了
> 
> 
> 
> 是的，因此我也没太搞清楚原因。“实名制入群”的功能需求已经达到，没能成功改名片，略有遗憾，影响不大。

我的机器人功能和您的类似，我刚开始也无法修改群名片，挂在那一段时间后正常了，可能是tx风控所致，您可以尝试下多挂一段时间并使用同一ip登录QQ安全中心网页版，尝试修改为短一些的群名片等措施，希望对您有帮助。

**Comment by SmileZXLee** [comment]
@yoonching 我有时候也会出现无法修改群名片的问题，收到新用户入群消息后，延时1秒再修改群名片似乎会好些。你可以试下。

**Comment by yoonching** [comment]
> @yoonching 我有时候也会出现无法修改群名片的问题，收到新用户入群消息后，延时1秒再修改群名片似乎会好些。你可以试下。

感谢您的提醒，我会在接下来的版本中测一下。

**Comment by yoonching** [comment]
> @yoonching 我有时候也会出现无法修改群名片的问题，收到新用户入群消息后，延时1秒再修改群名片似乎会好些。你可以试下。

感谢您的提醒，我会在接下来的版本中测一下。
