### ISSUE TITLE
关于mirai-native初始化时给自己发送信息导致的账户冻结问题

### ISSUE THREAD

**Issue by MemorySnow** [iTXTech/mirai-native#23]
请问作者，程序是否以初始化时给自己发的信息作为相关判断条件？经测试机器人在给自己发送这几条信息的时候会导致账号被腾讯冻结。我尝试以以下方法绕过给自己发消息的环节，但是这会导致程序判断机器人不在线从而无法enable插件：
1、重命名mirai-nativeXXX.jar为mirai-nativeXXX.jar.bak
2、启动mirai登录
3、把bak文件重命名为mirai-nativeXXX.jar
4、reload命令重载插件(此时程序以及成功加载并可以使用npm加载dll)
5、npm load XXXX.DLL（此时能够成功load，通过npm status可看到dll状态为已禁用 已加载）
6、npm enable XXXX.dll（此时dll无法enable，程序判定bot不在线，无法调用Enable事件）
经过此番操作，我推测开发者可能将该信息作为BOT状态的判断条件，故尝试手动发送，果不其然贵程序开始了初始化流程，然后账号再一次被冻结
**请问对于这种情况，是否有解决方案？**

**Comment by PeratX** [comment]
mirainative本身不会发送任何消息，只有api被调用才会发送，更多可能还是账号本身问题

**Comment by MemorySnow** [comment]
好的已造轮子解决了
