### ISSUE TITLE
接收到消息无法正常解析换行

### ISSUE THREAD

**Issue by BillYang2016** [iTXTech/mirai-native#24]
在聊天窗口收到换行，在控制台接收到的消息将不显示换行：
这是发送的消息：
![1](https://user-images.githubusercontent.com/26852391/89728678-b1ecf200-da61-11ea-8ad4-941d2dec8543.png)
这是控制台收到的消息：
![2](https://user-images.githubusercontent.com/26852391/89728679-b31e1f00-da61-11ea-85b7-cc162eb1f500.png)

而在插件里调用msg，换行后面的文字会被直接忽略
![3](https://user-images.githubusercontent.com/26852391/89728691-cdf09380-da61-11ea-8b37-bb01b1894cba.png)

更多的测试（未被完全验证）：
两个0宽字符就直接插件获取信息为空
插件似乎不能成功获取unicode字符？

**Comment by PeratX** [comment]
字符串编码采用GB18030，请用该编码测试。

**Comment by BillYang2016** [comment]
酷Q对msg的推送是GB18030格式，GB18030应该是支持全Unicode的，但是换行和多Unicode字符产生上述同样的问题。

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/89734085-6e5bad80-da8c-11ea-91da-176c331f95d9.png)

如图，经测试可以发送换行

**Comment by PeratX** [comment]
看了C艹那边的转码，应该是没有问题的，换行也能发，但是收到不管哪个客户端都是没有换行。

**Comment by BillYang2016** [comment]
经过了进一步测试，客户端推送给插件应该是带了换行的，但是是char(13)（以前用的char(10)），然而在命令行似乎不能经常以\n表示出来（有的时候可以，但大多数时候都被吃掉了）。

**Comment by PeratX** [comment]
正确的 `\n` 应该是 `10`，请确保字符串发送的是`\n`而不是`\r`

**Comment by BillYang2016** [comment]
接受到的msg推送是`\r (13)`，应该是处理问题

**Comment by PeratX** [comment]
这就取决于发送客户端那边的情况了

**Comment by mrhso** [comment]
酷 Q 把消息传递给插件时会把换行转为 CRLF，但是处理插件传过来的消息就不太清楚了。

**Comment by PeratX** [comment]
> 酷 Q 把消息传递给插件时会把换行转为 CRLF，但是处理插件传过来的消息就不太清楚了。

mirai这边的逻辑是接收到啥就下发啥，不做处理
