### ISSUE TITLE
EPL在eventGroupMsg内使用延时（）功能阻塞问题

### ISSUE THREAD

**Issue by zxin8580** [iTXTech/mirai-native#25]
当酷Q规范的插件在处理调用时如使用延时()或推迟执行子程序()，将使其他消息的处理一起暂停直到前面的线程(?)返回。请问Mirai是否可以实现酷Q的多线程不阻塞方式处理消息，感谢！

**Comment by PeratX** [comment]
没有懂你表达的意思呢

**Comment by PeratX** [comment]
如果事件内阻塞的话会导致整个native线程阻塞，但不会导致mirai阻塞
如果需要异步处理事件请使用相关API

**Comment by zxin8580** [comment]
> 没有懂你表达的意思呢

编写了一些游戏功能，实现方式用到延时（30000）以便在30秒后自动结束游戏并发出统计数据，其他用户可以在这30秒期间执行一些动作，酷Q环境下这种写法可以达到效果，日志里将会显示一条消息的处理时间为30秒

**Comment by PeratX** [comment]
> > 没有懂你表达的意思呢
> 
> 编写了一些游戏功能，实现方式用到延时（30000）以便在30秒后自动结束游戏并发出统计数据，其他用户可以在这30秒期间执行一些动作，酷Q环境下这种写法可以达到效果，日志里将会显示一条消息的处理时间为30秒

Native中**必须**使用异步方法来进行延时，切勿在事件内阻塞

**Comment by PeratX** [comment]
易语言有相关的API的，比如
`启动线程()`

**Comment by zxin8580** [comment]
> 易语言有相关的API的，比如
> `启动线程()`
> 你可以在线程中调用Mirai Native这个已经经过测试。

尝试过将mirai的所有事件都先传递给启动线程()并将fromgroup, msg等参数使用内存指针传递后处理，会导致运行错误

**Comment by PeratX** [comment]
> > 易语言有相关的API的，比如
> > `启动线程()`
> > 你可以在线程中调用Mirai Native这个已经经过测试。
> 
> 尝试过将mirai的所有事件都先传递给启动线程()并将fromgroup, msg等参数使用内存指针传递后处理，会导致运行错误

错误并未上报，这边无法处理

**Comment by zxin8580** [comment]
> > > 没有懂你表达的意思呢
> > 
> > 
> > 编写了一些游戏功能，实现方式用到延时（30000）以便在30秒后自动结束游戏并发出统计数据，其他用户可以在这30秒期间执行一些动作，酷Q环境下这种写法可以达到效果，日志里将会显示一条消息的处理时间为30秒
> 
> Native中**必须**使用异步方法来进行延时，切勿在事件内阻塞

弱弱问一句...能否考虑将native接收到的事件本身异步

**Comment by PeratX** [comment]
> > > > 没有懂你表达的意思呢
> > > 
> > > 
> > > 编写了一些游戏功能，实现方式用到延时（30000）以便在30秒后自动结束游戏并发出统计数据，其他用户可以在这30秒期间执行一些动作，酷Q环境下这种写法可以达到效果，日志里将会显示一条消息的处理时间为30秒
> > 
> > 
> > Native中**必须**使用异步方法来进行延时，切勿在事件内阻塞
> 
> 弱弱问一句...能否考虑将native接收到的事件本身异步

不考虑。

**Comment by PeratX** [comment]
能否上报多线程处理错误的复现代码？

**Comment by zxin8580** [comment]
> 能否上报多线程处理错误的复现代码？

稍等，那次弄完删文件了，现在正在尝试复现

**Comment by PeratX** [comment]
> > 能否上报多线程处理错误的复现代码？
> 
> 稍等，那次弄完删文件了，现在正在尝试复现

好的。

**Comment by zxin8580** [comment]
> > > 能否上报多线程处理错误的复现代码？
> > 
> > 
> > 稍等，那次弄完删文件了，现在正在尝试复现
> 
> 好的。

老哥，之前的异常不出现了，可能是我之前删掉的源码传递内存指针的时候有问题没处理好，当时异常提示是E程序崩溃，肯定也不是native的问题。刚刚尝试将native传递过来的参数以创建线程并传递指针的方式在新线程处理问题就解决了，非常感谢QAQ

**Comment by PeratX** [comment]
> > > > 能否上报多线程处理错误的复现代码？
> > > 
> > > 
> > > 稍等，那次弄完删文件了，现在正在尝试复现
> > 
> > 
> > 好的。
> 
> 老哥，之前的异常不出现了，可能是我之前删掉的源码传递内存指针的时候有问题没处理好，当时异常提示是E程序崩溃，肯定也不是native的问题。刚刚尝试将native传递过来的参数以创建线程并传递指针的方式在新线程处理问题就解决了，非常感谢QAQ

不客气呢。

**Comment by lulu666lulu** [comment]
在mirai-native中打开插件窗口也会导致阻塞，关闭后就可以了，这个有办法解决吗？

**Comment by PeratX** [comment]
> 在mirai-native中打开插件窗口也会导致阻塞，关闭后就可以了，这个有办法解决吗？

窗口内是否执行阻塞方法，请检查。

**Comment by lulu666lulu** [comment]
用的别人的插件，只要一开窗口由native加载的插件就全部不工作了。

**Comment by PeratX** [comment]
> 用的别人的插件，只要一开窗口由native加载的插件就全部不工作了。

窗口是否卡住？

**Comment by lulu666lulu** [comment]
窗口可以操作，但是所有消息不处理，关闭窗口就可以处理了

**Comment by Pika-Lee** [comment]
> 窗口可以操作，但是所有消息不处理，关闭窗口就可以处理了

我也遇到了这个情况，开启窗口后native就阻塞了，关闭窗口后才会继续处理之前的所有消息。

测试了一下，不止一个插件有这个问题，很多有窗口的插件开启后都会阻塞。

**Comment by PeratX** [comment]
这个主要还是插件的逻辑有问题，日后可能会修改`mirai native`整体运行逻辑
