### ISSUE TITLE
关于群消息响应中附加异常处理后，消息发送完之后会NATIVE闪退

### ISSUE THREAD

**Issue by dragon0629** [iTXTech/mirai-native#26]
群消息响应事件中如果进行了TRY处理，会导致消息发送成功后NATIVE闪退。

传了个测试插件，带界面，功能只有一个 ：收到群消息时，复读一次群消息

http://118.24.72.13/testMiraiNative.zip

当界面不勾选TRY的时候，直接复读群消息成功，NATIVE依旧运行
当界面勾选TRY的时候，直接复读群消息也成功，但复读完之后，NATIVE托盘闪退

代码逻辑就是不勾选的时候直接复读，勾选的时候用了TRY复读

发现原因是因为群聊命令查一些API接口信息之后，正常得到了查询结果，也正常发送了群消息，但之后NATIVE托盘立刻闪退，排查到最后是发现群聊的整条逻辑里只要用了TRY，成功发送完消息之后必闪退

但是正常的监听线程里用TRY都没事。

此类插件之前酷Q可稳定运行。

**Comment by PeratX** [comment]
所谓闪退必然是java进程崩溃了，请提交崩溃日志
另不接受插件二进制文件，如果需要协助调查必须提供源代码。

**Comment by dragon0629** [comment]
感谢这么快回复！！！！

http://118.24.72.13/%E6%BA%90%E7%A0%81%E6%A8%A1%E5%9D%97.zip

传了，主要不少老插件还是几年前用易语言写的，见笑了。
用的3个模块是酷QSDK，精易官方，异常处理

另外这个崩溃没有看到崩溃日志在哪里，就是鼠标移到托盘处发现图标就消失了。

然后console窗口处没有响应，回车一下提示

[16:35:16.7127] E 运行失败，尝试更新mirai三件套 exit status -1073741819
[16:35:17.3898] E 无法启动 exec: already started

我马上回头用C#再测一测看看，主要之前的很多老插件实在没办法了。去掉TRY就能用，不去掉群聊就没法用，但主动监听推送到群都是一切正常的。

**Comment by PeratX** [comment]
用mirai-console-wrapper启动尝试，不要使用miraiok

**Comment by PeratX** [comment]
这个你可以看下我写的test.e里面也没用到异常处理，这个在大多数情况下不是必须的，具体问题还要看异常处理这个模块的代码。

**Comment by PeratX** [comment]
看了一下，确实没有崩溃信息，这种情况应该是直接段错误了（内存错误

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/90004170-cd593680-dcc7-11ea-8f03-858a306ee453.png)
VS调试器显示崩溃源不在native中

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/90004360-127d6880-dcc8-11ea-909b-c495e19664ec.png)

**Comment by dragon0629** [comment]
感谢，请问大佬的test.e 在哪里，我找了一下没有找到。

然后反馈一下我又使用c#的nativesdk 发布酷Q插件，进行消息回复，结果群消息错误的更严重了。
发消息还没TRY直接就是致命错误,log日志已上传
http://118.24.72.13/groupmsgerror_c.log

逻辑源码就一行:
		public void ReceiveGroupMessage (object sender, GroupMessageEventArgs e)
		{
			Common.CqApi.AddLoger(Sdk.Cqp.Enum.LogerLevel.Info, "群聊", "信息");
			Common.CqApi.SendGroupMessage (e.FromGroup, e.FromAnonymous.CodeName + " 你发送了这样的消息: " + e.Msg);
            e.Handled = false;   // 关于返回说明, 请参见 "Event_FriendMessage.ReceiveFriendMessage" 方法
		}

那条群聊信息的日志在console里是打出来了，

**Comment by dragon0629** [comment]
总之非常感谢大佬，目前靠MIRAI NATIVE恢复了95%的使用功能，^-^谢谢

**Comment by PeratX** [comment]
这个看了一下，C#这边错误也不在mirai native，用Native.SDK的人也不少，考虑还是本身代码的问题。
[test.e](https://github.com/iTXTech/mirai-native/blob/master/epl-test/test.e)

**Comment by PeratX** [comment]
```
0x03719857 处(位于 java.exe 中)引发的异常: 0xC0000005: 写入位置 0x00000290 时发生访问冲突。
0xE77FCCE0 处有未经处理的异常(在 java.exe 中): 0xC00001A5: 检测到无效的异常处理程序例程。 (参数: 0x00000003)。
```
这是调试器输出的错误，应该是异常处理模块的问题

**Comment by dragon0629** [comment]
好的，回头更新一下nativesdk到最新版，升级一下CQP.DLL再试试
另外历程中附带的mnsdk.ec麻烦可以提供一下嘛，MIRAI官方群现在进不去，囧rz...

**Comment by PeratX** [comment]
> 好的，回头更新一下nativesdk到最新版，升级一下CQP.DLL再试试
> 另外历程中附带的mnsdk.ec麻烦可以提供一下嘛，MIRAI官方群现在进不去，囧rz...

那个还没有完成呢，暂时不要使用

**Comment by PeratX** [comment]
> 好的，回头更新一下nativesdk到最新版，升级一下CQP.DLL再试试
> 另外历程中附带的mnsdk.ec麻烦可以提供一下嘛，MIRAI官方群现在进不去，囧rz...

`mnsdk.ec`从`sdk.e`编译来的，目前只能引用回复消息

**Comment by dragon0629** [comment]
好的，非常感谢！

**Comment by PeratX** [comment]
有更多情况可以继续跟进，现在暂时关闭，因为问题不在mirai native
