### ISSUE TITLE
Wine 下无 CP 54936

### ISSUE THREAD

**Issue by mrhso** [iTXTech/mirai-native#32]
GB 18030 转换部分依赖 Windows 的原生 API，然而 Wine 下并没有 CP 54936。
也许可以引入 libiconv。当然，现在的 libiconv 并不遵循 GB 18030-2000，所以可以使用我修改过的 libiconv。
考虑到 libiconv 是 LGPL，我把 Patch 也附上了。
[libiconv 1.16 GB 18030-2000.7z](https://github.com/iTXTech/mirai-native/files/5070065/libiconv.1.16.GB.18030-2000.zip)

**Comment by PeratX** [comment]
> GB 18030 转换部分依赖 Windows 的原生 API，然而 Wine 下并没有 CP 54936。
> 也许可以引入 libiconv。当然，现在的 libiconv 并不遵循 GB 18030-2000，所以可以使用我修改过的 libiconv。
> 考虑到 libiconv 是 LGPL，我把 Patch 也附上了。
> [libiconv 1.16 GB 18030-2000.7z](https://github.com/iTXTech/mirai-native/files/5070065/libiconv.1.16.GB.18030-2000.zip)

本来考虑的解决方案是可配置的codepage

**Comment by PeratX** [comment]
看了一下，wine应该有936的，那就可以配置成936

**Comment by PeratX** [comment]
可配置的codepage已更新

**Comment by mrhso** [comment]
不过设成 CP 936 的话倒是有个问题，GB 18030 是 UTF，但 GBK 不是。

**Comment by PeratX** [comment]
> 不过设成 CP 936 的话倒是有个问题，GB 18030 是 UTF，但 GBK 不是。

能兼容中文字符集的插件就行了，当然需要考虑一些特殊转义，比如CQ中的emoji在GBK中可能就不存在了（是不是这样？

**Comment by mrhso** [comment]
> 能兼容中文字符集的插件就行了
（总感觉……）
> 当然需要考虑一些特殊转义，比如CQ中的emoji在GBK中可能就不存在了（是不是这样？
然而就算用了 CQ:emoji，用原生绘文字字符发送的插件同样完蛋……

**Comment by PeratX** [comment]
> > 能兼容中文字符集的插件就行了
> 
> （总感觉……）
> 
> > 当然需要考虑一些特殊转义，比如CQ中的emoji在GBK中可能就不存在了（是不是这样？
> 
> 然而就算用了 CQ:emoji，用原生绘文字字符发送的插件同样完蛋……（毕竟非易语言插件也不少）

那可以直接配置成UTF的codepage呀

**Comment by mrhso** [comment]
`length * 2 + 1`

**Comment by PeratX** [comment]
可能是单字节编码转换到双字节编码需要两倍的空间，结尾还要多加个\0，所以+1
而且试过不+1会溢出错误。。。

**Comment by mrhso** [comment]
> 可能是单字节编码转换到双字节编码需要两倍的空间，结尾还要多加个\0，所以+1
> 而且试过不+1会溢出错误。。。

那为甚么不是 +2？
（0x00 0x00）

**Comment by PeratX** [comment]
> > 可能是单字节编码转换到双字节编码需要两倍的空间，结尾还要多加个\0，所以+1
> > 而且试过不+1会溢出错误。。。
> 
> 那为甚么不是 +2？
> （0x00 0x00）

其实是看csdn+StackOverflow写的这块

**Comment by Prcuvu** [comment]
https://github.com/iTXTech/mirai-native/blob/master/native/native.cpp#L34-L38

`JstringToGb` 函数中，`GetStringLength` 函数得到的是字节数吗？如果是完整字符的个数，是不行的。

参见：[MultiByteToWideChar function (stringapiset.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar)
> ### -param cbMultiByte [in]
> Size, **in bytes**, of the string indicated by the <i>lpMultiByteStr</i> parameter. Alternatively, this parameter can be set to -1 if the string is null-terminated. Note that, if <i>cbMultiByte</i> is 0, the function fails.
> If this parameter is -1, the function processes the entire input string, including the terminating null character. Therefore, the resulting Unicode string has a terminating null character, and the length returned by the function includes this character.
> If this parameter is set to a positive integer, the function processes exactly the specified number of bytes. If the provided size does not include a terminating null character, the resulting Unicode string is not null-terminated, and the returned length does not include this character.

> ### -param cchWideChar [in]
> Size, in characters, of the buffer indicated by <i>lpWideCharStr</i>. If this value is 0, the function returns the required buffer size, in characters, **including any terminating null character**, and makes no use of the <i>lpWideCharStr</i> buffer.

**Comment by PeratX** [comment]
如果觉得有问题可以直接pr，这个我不懂。
