### ISSUE TITLE
Native部分中的内存泄漏

### ISSUE THREAD

**Issue by w4123** [iTXTech/mirai-native#33]
Native部分的函数JstringtoGb，JstringToChars等都没有对分配的内存进行释放，而是直接交给了插件
根据酷Q的逻辑，应用禁止对这些字符串进行内存释放
因此，这会造成较为严重的内存泄漏

**Comment by PeratX** [comment]
那么怎么释放？（C++新手

**Comment by w4123** [comment]
其实我也在想这个问题因为这个真的不好写，如果是事件调用就直接事件结束后释放就可以，但是API调用就不好做

酷Q作者：
```
关于内存释放
酷Q V9 应用机制中包含了一部分涉及字符串 const char* 的参数及返回值。酷Q V9 中均要求内存申请方负责释放。

具体规则如下：

对于 Event 的字符串参数，酷Q 将负责在事件函数返回后立即释放。
在部分场景下，参数可能传入空指针 NULL，应用应判断该情况，避免读取空指针发生致命错误。
对于 Api 的字符串参数，应用负责在调用完后进行释放。
对于 Api 的字符串返回值，酷Q 将负责在合适的时机进行释放。
应用不应对字符串返回值进行释放，否则一段时间后，酷Q 尝试释放该内存时将发生致命错误。
应用应在调用 Api 后之后立即使用返回的指针，避免 酷Q 释放内存后，应用使用该指针时发生致命错误。
如果 Api 调用失败，将返回空指针 NULL，应用应判断该情况，避免读取空指针发生致命错误。
```

我也不知道这个"合适的时机"到底是怎么实现的，但是最有可能的我觉得是定时（比如申请内存五分钟以后释放之类的），直接使用比如static变量或者全局变量的方式都会把线程安全性破坏掉……

我这几天试着写一下没问题我会PR上来

**Comment by PeratX** [comment]
> 其实我也在想这个问题因为这个真的不好写，如果是事件调用就直接事件结束后释放就可以，但是API调用就不好做
> 
> 酷Q作者：
> 
> ```
> 关于内存释放
> 酷Q V9 应用机制中包含了一部分涉及字符串 const char* 的参数及返回值。酷Q V9 中均要求内存申请方负责释放。
> 
> 具体规则如下：
> 
> 对于 Event 的字符串参数，酷Q 将负责在事件函数返回后立即释放。
> 在部分场景下，参数可能传入空指针 NULL，应用应判断该情况，避免读取空指针发生致命错误。
> 对于 Api 的字符串参数，应用负责在调用完后进行释放。
> 对于 Api 的字符串返回值，酷Q 将负责在合适的时机进行释放。
> 应用不应对字符串返回值进行释放，否则一段时间后，酷Q 尝试释放该内存时将发生致命错误。
> 应用应在调用 Api 后之后立即使用返回的指针，避免 酷Q 释放内存后，应用使用该指针时发生致命错误。
> 如果 Api 调用失败，将返回空指针 NULL，应用应判断该情况，避免读取空指针发生致命错误。
> ```
> 
> 我也不知道这个"合适的时机"到底是怎么实现的，但是最有可能的我觉得是定时（比如申请内存五分钟以后释放之类的），直接使用比如static变量或者全局变量的方式都会把线程安全性破坏掉……
> 
> 我这几天试着写一下没问题我会PR上来

好的，我一开始也有考虑这个问题，但是才疏学浅没有找到合适的方法就一直搁置了，本来想引入智能指针的来着。。。

**Comment by PeratX** [comment]
在事件中创建的还是比较容易释放的
但是作为API返回的，就不知道怎么释放了

**Comment by PeratX** [comment]
是不是能启动一个线程，然后用一个队列，新占用的内存用指针的形式push入队列并设置5min的超市，线程中无限循环延时1秒取出超时的指针并free掉

**Comment by w4123** [comment]
是的 我也是这么想的

**Comment by PeratX** [comment]
> 是的 我也是这么想的

然而我不会写。。。如果是java就很容易了 😢

**Comment by PeratX** [comment]
您好，我尝试了在事件中delete 由`JstringToGb`创建的变量，会导致崩溃，向您请教原因，代码已经commit。

**Comment by w4123** [comment]
> 您好，我尝试了在事件中delete 由`JstringToGb`创建的变量，会导致崩溃，向您请教原因，代码已经commit。

malloc申请的内存用free释放（C语言方式，strdup也属于malloc）
new申请的内存用delete（单个变量）或者delete[]（数组）释放（C++方式）

**Comment by PeratX** [comment]
> > 您好，我尝试了在事件中delete 由`JstringToGb`创建的变量，会导致崩溃，向您请教原因，代码已经commit。
> 
> malloc申请的内存用free释放（C语言方式，strdup也属于malloc）
> new申请的内存用delete（单个变量）或者delete[]（数组）释放（C++方式）

确实，会崩溃。。。

**Comment by w4123** [comment]
> > > 您好，我尝试了在事件中delete 由`JstringToGb`创建的变量，会导致崩溃，向您请教原因，代码已经commit。
> > 
> > 
> > malloc申请的内存用free释放（C语言方式，strdup也属于malloc）
> > new申请的内存用delete（单个变量）或者delete[]（数组）释放（C++方式）
> 
> 确实，会崩溃。。。

我找到崩溃的原因了……不过这个崩溃的根本原因很可能是另一个bug……让我测试一会我等下反馈

**Comment by BillYang2016** [comment]
![1](https://user-images.githubusercontent.com/26852391/90465282-a1173d00-e141-11ea-903e-33a5df10fafd.png)
做了一下1.8.6的测试，内存泄漏的问题可能没有完美解决，在一个缓存的过程中，中间过程内存释放很好，但是结束缓存后很长的一段时间都没有对使用的内存进行回收？
用到的全局数组结束后已全部清空，且局部变量应该会自动销毁？

**Comment by PeratX** [comment]
> ![1](https://user-images.githubusercontent.com/26852391/90465282-a1173d00-e141-11ea-903e-33a5df10fafd.png)
> 做了一下1.8.6的测试，内存泄漏的问题可能没有完美解决，在一个缓存的过程中，中间过程内存释放很好，但是结束缓存后很长的一段时间都没有对使用的内存进行回收？
> 用到的全局数组结束后已全部清空，且局部变量应该会自动销毁？

native层面要管理的内存仅限于native创建的const char*，这些字符串自动回收是5分钟的超时，您说的图片情况考虑是jvm的内存突增

**Comment by PeratX** [comment]
变量如果是new或者malloc出来的需要需要delete或者free手动释放的

**Comment by BillYang2016** [comment]
图片是使用gdiplus进行的处理，其中的对象应该全部销毁了，另外应该没有用到new和malloc，我稍后再检查一下

**Comment by PeratX** [comment]
> 图片是使用gdiplus进行的处理，其中的对象应该全部销毁了，另外应该没有用到new和malloc，我稍后再检查一下

可以配合调试器查看内存占用情况，native内不会处理图片的，都是插件自行读写处理
