### ISSUE TITLE
机器人已入群事件的处理

### ISSUE THREAD

**Issue by w4123** [iTXTech/mirai-native#34]
我发现当前mirai-native对于机器人已被邀请进群事件的处理逻辑是如果机器人同意了申请便触发此事件
然而这并不是总是正确的，比如如果邀请机器人加入群的人不是管理员，那么机器人要管理员审核后才真正进入了群（这也符合酷Q的逻辑）
我看到Mirai有一个事件是BotJoinGroupEvent，或许应该改为这个事件？

**Comment by PeratX** [comment]
是这个道理，但是这个事件本身不稳定，不过还是先按照您说的修改，这样确实更符合逻辑。
