### ISSUE TITLE
关于npm命令使用方法

### ISSUE THREAD

**Issue by fvffv** [iTXTech/mirai-native#37]
请问npm指令如何使用加载/卸载插件
这样写npm load F:\MiraiOK\MiraiOK\plugins\MiraiNative\plugins\cd.dll
还是这样写npm load cd.dll
都显示文件不存在

**Comment by PeratX** [comment]
请给出具体文件系统目录结构，以及具体报错信息

**Comment by fvffv** [comment]
> 请给出具体文件系统目录结构，以及具体报错信息

假设我的DLL和JSON在F:\MiraiOK\MiraiOK\plugins\MiraiNative\plugins目录下  DLL名字为chajian.dll JSON名字为chajian.json
我该如何使用npm命令直接导入 这个插件呢

**Comment by PeratX** [comment]
npm load chajian.dll

**Comment by fvffv** [comment]
> npm load chajian.dll

可他却提示[Command] 文件 chajian.dll 不存在

**Comment by PeratX** [comment]
> > npm load chajian.dll
> 
> 可他却提示[Command] 文件 chajian.dll 不存在

**所以要求您给出目录结构(tree)命令，以及完整的日志。**

**Comment by fvffv** [comment]
> > > npm load chajian.dll
> > 
> > 
> > 可他却提示[Command] 文件 chajian.dll 不存在
> 
> **所以要求您给出目录结构(tree)命令，以及完整的日志。**

我该如何给出呢 log里面是空的

**Comment by fvffv** [comment]
> > > > npm load chajian.dll
> > > 
> > > 
> > > 可他却提示[Command] 文件 chajian.dll 不存在
> > 
> > 
> > **所以要求您给出目录结构(tree)命令，以及完整的日志。**
> 
> 我该如何给出呢 log里面是空的

F:\MiraiOK\MiraiOK\plugins\MiraiNative\plugins

**Comment by PeratX** [comment]
确实是个bug，这个bug要求放在`MiraiNative`中才能被动态加载

**Comment by fvffv** [comment]
> 确实是个bug，这个bug要求放在`MiraiNative`中才能被动态加载

好的 谢谢啦 可以尽快修复嘛

**Comment by PeratX** [comment]
已修复，预计几天发布新版本

**Comment by fvffv** [comment]
> 已修复，预计今天发布新版本

我可以在哪里下载到最新的插件

**Comment by PeratX** [comment]
[Releases](https://github.com/iTXTech/mirai-native/releases)

**Comment by fvffv** [comment]
> [Releases](https://github.com/iTXTech/mirai-native/releases)

好的 顺便问一下unload 只能通过插件ID来卸载吗 能否从插件文件名卸载

**Comment by PeratX** [comment]
只能使用插件id

**Comment by Pika-Lee** [comment]
> 确实是个bug，这个bug要求放在`MiraiNative`中才能被动态加载

所以native 1.8.5及之后的版本将动态加载的文件夹改成了plugins\MiraiNative\plugins吗？但是**这个目录下的dll应该在运行mirai_ok的时候就已经被自动加载**了吧？似乎没有必要再手动发送npm load命令了吧？（除非需要unload再load的时候才会用到）

感觉还是之前的动态加载文件夹位置plugins\MiraiNative\用处更大一些，我在[#53](https://github.com/iTXTech/mirai-native/issues/53) 中也提到了其中一种用法（比如可以实现机器人登陆后再加载某插件）
![00](https://user-images.githubusercontent.com/23114990/91026593-89eaba80-e62d-11ea-8412-4f4236e88687.png)
![01](https://user-images.githubusercontent.com/23114990/91026607-8eaf6e80-e62d-11ea-970a-bf22cef1f945.png)
![02](https://user-images.githubusercontent.com/23114990/91026611-90793200-e62d-11ea-931a-0c60a5af67be.png)
![03](https://user-images.githubusercontent.com/23114990/91026615-9242f580-e62d-11ea-9551-3983c018ccba.png)
![04](https://user-images.githubusercontent.com/23114990/91026619-940cb900-e62d-11ea-8bcb-cc747da03548.png)

题主的需求，其实可以通过将dll和json放到plugins\MiraiNative\，然后发送npm load/unload来解决。个人觉得其实没必要改动位置到plugins\MiraiNative\plugins，因为这里面的文件在运行mirai_ok的时候就已经被自动加载了，放到原先的位置plugins\MiraiNative\会更有意义一些。

**Comment by PeratX** [comment]
现在已经修改成登录之后再启用所有插件了，请等待近期新版本发布，将适配`mirai console 1.0-M3`

**Comment by Pika-Lee** [comment]
个人觉得，原先npm的目录放在\MiraiNative并非BUG，有其存在的理由。比如可以有别于\MiraiNative\plugins的“自动加载”，通过npm load XXX.dll指令从另一个目录（\MiraiNative）来**手动加载插件**。这样可以方便开发者在机器人运行时**动态加载/卸载插件**（\MiraiNative\plugins里面的dll在机器人运行时是存在**写保护**的），方便开发者进行调试，而不用每次都重启Mirai。
![写保护](https://user-images.githubusercontent.com/23114990/91029105-ee5b4900-e630-11ea-9d38-1efd16058ec0.png)

> 好的 顺便问一下unload 只能通过插件ID来卸载吗 能否从插件文件名卸载
> 只能使用插件id
而对于已加载的插件，也**可以且仅能**通过npm unload id来进行管理（不能用npm unload XXX.dll），这似乎也从另一方面体现了npm load/unload设计时便考虑到了从外部位置动态加载/卸载插件的使用场景。（动态加载后的插件并没有导入\MiraiNative\plugins，依然位于\MiraiNative，所以不能用npm unload XXX.dll指令来处理\MiraiNative\plugins外的dll）

当然以上只是个人揣测，重启一遍mirai本身也并不麻烦。所以不论npm的位置是在\MiraiNative还是\MiraiNative\plugins其实也都无所谓，对开发者的影响不是很大。

> 现在已经修改成登录之后再启用所有插件了，请等待近期新版本发布，将适配`mirai console 1.0-M3`
感谢答复，期待新版本的到来，期待mirai能为CQ插件带来更好的适配。

**Comment by PeratX** [comment]
您看这样，不如让load的底层实现支持从绝对路径加载插件

**Comment by Pika-Lee** [comment]
> 您看这样，不如让load的底层实现支持从绝对路径加载插件

可以，绝对路径或者直接改回到原来的位置\MiraiNative，这两种方案都可以，看您更倾向于哪一种了。

![05](https://user-images.githubusercontent.com/23114990/91034396-865c3100-e637-11ea-8233-60770eeec635.png)

![00](https://user-images.githubusercontent.com/23114990/91034268-5319a200-e637-11ea-81c3-54e2c57b2fb9.png)

刚刚发现系统托盘里的“加载DLL”其实就是调用的npm load XXX.dll指令（您如果打算改成绝对路径的话，这里也需要再调整一下，将dll名改成绝对路径地址）

**Comment by PeratX** [comment]
这两个底层都是同一个函数

**Comment by Pika-Lee** [comment]
> 这两个底层都是同一个函数

那就方便改动了。绝对路径的适用性更强，但可能会破坏一体性（比如dll位于mirai根目录外）；固定路径的话更简单直接一些，直接输入dll名也比路径名方便。\MiraiNative和\MiraiNative\plugins距离也挺近的，两个位置之间的文件移动操作也挺方便。

这几天我经常用到npm load，对\MiraiNative的目录结构也有了一些自己的理解。
\MiraiNative\plugins相当于某Q的\data\app，正式版的插件放在这里供用户使用。
\MiraiNative相当于某Q的\dev，便于开发者动态加载/卸载插件，随时进行调试。

如此看来，感觉原来的\MiraiNative的位置似乎也不错，当然您如果打算改成绝对路径也是可以的。

**Comment by fvffv** [comment]
> 这两个底层都是同一个函数

如果可以的话 希望可以通过dll文件名来卸载插件 而不是id  如果不可以的话请问这个数字id是如何计算的呢

**Comment by Pika-Lee** [comment]
> > 这两个底层都是同一个函数
> 
> 如果可以的话 希望可以通过dll文件名来卸载插件 而不是id 如果不可以的话请问这个数字id是如何计算的呢

这个id应该是mirai所有已加载插件的编号吧，具体是如何排序的我没注意过。不过据我观察，通过npm load手动加载的插件id应该是位于最后的。至于不能用dll卸载的原因，我前面的回复中已经有过分析（不知道对不对，我没研究过mirai底层代码）。不过插件既然已经被加载了，id应该也是固定的，你可以发送npm list查看插件对应的id，然后用npm unload id来卸载插件。

**Comment by PeratX** [comment]
id是按照插件被列出的顺序（即listFiles的顺序）递增的

**Comment by fvffv** [comment]
> > > 这两个底层都是同一个函数
> > 
> > 
> > 如果可以的话 希望可以通过dll文件名来卸载插件 而不是id 如果不可以的话请问这个数字id是如何计算的呢
> 
> 这个id应该是mirai所有已加载插件的编号吧，具体是如何排序的我没注意过。不过据我观察，通过npm load手动加载的插件id应该是位于最后的。至于不能用dll卸载的原因，我前面的回复中已经有过分析（不知道对不对，我没研究过mirai底层代码）。不过插件既然已经被加载了，id应该也是固定的，你可以发送npm list查看插件对应的id，然后用npm unload id来卸载插件。

本人是想用外部程序控制mirai来写一个完整图形界面 方便操作 但没办法直接获取到插件对应id 这点就比较麻烦了 无法实现通过外部程序卸载插件

**Comment by PeratX** [comment]
可以直接写Java GUI并提交到本仓库的

**Comment by fvffv** [comment]
> 可以直接写Java GUI并提交到本仓库的

javagui 本人也并不了解，无能为力 个人觉得用其他编程语言写gui还是比较方便的

**Comment by PeratX** [comment]
说说你的想法，现在的菜单的不足？
其他语言无法调用`Mirai Native`提供的插件管理API，是非常不便的

**Comment by fvffv** [comment]
> 说说你的想法，现在的菜单的不足？
> 其他语言无法调用`Mirai Native`提供的插件管理API，是非常不便的

其实并非是mn插件不足 本人觉得已经做的很不错啦 主要还是mirai没有图形界面 这一点这样就会阻挡一部分使用者使用 所以我才写了一个gui界面套在mirai 上控制全局，目前已发布到一个群中 使使用者一目了然，而并非杂乱的cmd窗口

**Comment by PeratX** [comment]
在可见的未来，`mirai console`也会有图形化前端的。

**Comment by fvffv** [comment]
> 在可见的未来，`mirai console`也会有图形化前端的。

还有个问题😅 mirai更新所发布的文件不集中不容易找到最新版下载地址 如果可以希望可以集中发布

**Comment by PeratX** [comment]
见[mirai-repo](https://github.com/project-mirai/mirai-repo/tree/master/shadow)
[bintray](https://bintray.com/him188moe/mirai)
