### ISSUE TITLE
关于获取网络图片链接

### ISSUE THREAD

**Issue by laomms** [iTXTech/mirai-native#38]
发送网络图片以 .mnimg 结尾，该文件不落地，例：[CQ:image,file={247E6A8B-ED3A-1B98-15E8-07E2277C787A}.jpg.mnimg]

如何提取该图片链接或者保存该文件用于识别 ?

**Comment by PeratX** [comment]
`getImage("{247E6A8B-ED3A-1B98-15E8-07E2277C787A}.jpg.mnimg"`)`将返回图片下载后的绝对路径

**Comment by laomms** [comment]
GetImage("{247E6A8B-ED3A-1B98-15E8-07E2277C787A}.jpg.mnimg") 第一次正常保存图片，第二次崩溃:

`Internal exceptions (10 events):
Event: 1.434 Thread 0x0071e400 Exception <a 'java/io/FileNotFoundException'> (0x049f5178) thrown at [J:\jenkins\tmp\workspace\build\src\hotspot\src\share\vm\prims\jni.cpp, line 710]
Event: 1.434 Thread 0x0071e400 Exception <a 'java/lang/NullPointerException'> (0x049f5908) thrown at [J:\jenkins\tmp\workspace\build\src\hotspot\src\share\vm\interpreter\linkResolver.cpp, line 1185]
Event: 8.344 Thread 0x166c5c00 Exception <a 'java/lang/ClassCastException': java.util.AbstractMap$SimpleImmutableEntry cannot be cast to java.util.Map> (0x04b91d28) thrown at [J:\jenkins\tmp\workspace\build\src\hotspot\src\share\vm\interpreter\interpreterRuntime.cpp, line 383]`

**Comment by PeratX** [comment]
你提供的崩溃信息不包含任何有用的信息。

**Comment by laomms** [comment]
已经解决, 是由于插件在识别时HttpWebResponse未释放引起内存溢出. 原来用HttpWebResponse.Close(),改为HttpWebResponse.Dispose()解决,奇怪的是以前用酷Q一直没问题.

**Comment by PeratX** [comment]
> 已经解决, 是由于插件在识别时HttpWebResponse未释放引起内存溢出. 原来用HttpWebResponse.Close(),改为HttpWebResponse.Dispose()解决,奇怪的是以前用酷Q一直没问题.

可能是的`JNI`的限制，解决了就好
