### ISSUE TITLE
执行控制台命令

### ISSUE THREAD

**Issue by fvffv** [iTXTech/mirai-native#39]
有没有什么命令可以直接向mirai控制台发送命令

**Comment by PeratX** [comment]
请问您想实现什么效果？

**Comment by fvffv** [comment]
> 请问您想实现什么效果？

即可以在易语言中使用命令 在mirai控制台执行npm命令

**Comment by PeratX** [comment]
原生CQ中并没有相关方法，所以native可能不会考虑实现该方法。

**Comment by fvffv** [comment]
> 原生CQ中并没有相关方法，所以native可能不会考虑实现该方法。

其实我最终目的是想写一个插件管理界面
自带的太2333

**Comment by PeratX** [comment]
> > 原生CQ中并没有相关方法，所以native可能不会考虑实现该方法。
> 
> 其实我最终目的是想写一个插件管理界面
> 自带的太2333

有啥想法可以说出来讨论，这个建议在`kotlin`层面实现

**Comment by fvffv** [comment]
> > > 原生CQ中并没有相关方法，所以native可能不会考虑实现该方法。
> > 
> > 
> > 其实我最终目的是想写一个插件管理界面
> > 自带的太2333
> 
> 有啥想法可以说出来讨论，这个建议在`kotlin`层面实现

emm 最好加个自动更新的

**Comment by fvffv** [comment]
> > > 原生CQ中并没有相关方法，所以native可能不会考虑实现该方法。
> > 
> > 
> > 其实我最终目的是想写一个插件管理界面
> > 自带的太2333
> 
> 有啥想法可以说出来讨论，这个建议在`kotlin`层面实现

还有个问题 当用npm加载插件的时候 若插件名称为中文名 输入后按回车会变成乱码 估计是UTF8转码的原因

**Comment by PeratX** [comment]
关于自动更新：原本console的插件管理是有支持自动更新的计划的，console 1.0也在大力推进，不过收到一系列事件影响，被迫推迟
关于乱码：可能是终端编码的问题，建议还是不要用中文名或者让native自动加载
