### ISSUE TITLE
报个1.8.5的加载的CQP.DLL 报错小问题

### ISSUE THREAD

**Issue by dragon0629** [iTXTech/mirai-native#40]
1.8.4完全正常加载

更换1.8.5后启动报错，NATIVE加载失败
检查日志发现1.8.5提示CQP.dll 的检查失败，之后导致一连串的报错，native启动失败
后删除CQP.DLL之后，重新写到本地的CQP.DLL可以正常加载1.8.5。
可能这里是个breakchange

不过该错已解决，但对于升级用户来说可能不注意这个，小问题。

**Comment by PeratX** [comment]
确实有向后不兼容的更改，
1.8.5新增可配置的codepage，为了实现这个，添加了一个config方法，这在之前的`CQP.dll`中不存在，所以会报错
