### ISSUE TITLE
on_private_message事件未触发

### ISSUE THREAD

**Issue by dynilath** [iTXTech/mirai-native#41]
把[这么](https://github.com/dynilath/coolq-dicebot/releases/tag/1.7.4a)个项目弄进`mirai-native`时遇到了一些问题。

`on_group_message`事件能够被正常触发。  
`on_private_message`事件无法通过`FriendMessageEvent`触发。

**Comment by PeratX** [comment]
在看了在看了
口古口古口古

**Comment by PeratX** [comment]
看了一下，native这边监听代码没有问题，考虑还是mirai那边的问题
方便截图一下日志吗？

**Comment by PeratX** [comment]
已确认是`mirai core`的问题

**Comment by PeratX** [comment]
mirai core已unarchive，请向其汇报该问题。
