### ISSUE TITLE
已经载入了外部库，但是依然提示错误126.

### ISSUE THREAD

**Issue by lizkes** [iTXTech/mirai-native#43]
在ubuntu18.04+wine5.03环境下，使用miraiOK+mirai-native加载coolq-http-api插件提示code126
![snipaste_20200816_103155](https://user-images.githubusercontent.com/20457790/90325243-bbb7ad80-dfab-11ea-8b77-f76c3f31888d.png)

在windows10环境下，使用miraiOK+mirai-native加载coolq-http-api插件是正常的code0
![snipaste_20200816_103421](https://user-images.githubusercontent.com/20457790/90325264-105b2880-dfac-11ea-9d88-66b0142948b4.png)

请问这是什么情况呢

**Comment by PeratX** [comment]
可能还少了其他东西，比如VC运行时之类的

**Comment by PeratX** [comment]
`CQHTTP`依赖以下dll
```
    libiconv.dll
    sqlite3.dll
    CRYPT32.dll
    KERNEL32.dll
    USER32.dll
    ADVAPI32.dll
    MSVCP140.dll
    WS2_32.dll
    MSWSOCK.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-conio-l1-1-0.dll
```
api-ms-win-crt开头的都是VC++运行时

**Comment by lizkes** [comment]
经过反复的测试最后还是放弃了，wine已经有了上述所有依赖但还是code126
迫不得已还是DD了windows系统，已经可以成功使用了

**Comment by PeratX** [comment]
好的，有空出个wine docker
