### ISSUE TITLE
eventRequestAddFriend 与 eventRequestAddGroup 的 message

### ISSUE THREAD

**Issue by mrhso** [iTXTech/mirai-native#44]
酷 Q 中这两个事件的附言其实是和一般消息相同的，也就是都有 CQ 码，甚至会出现 `[CQ:emoji]`。
当然 mirai-native 肯定是不做 `[CQ:emoji]` 的，但是我觉得转义大概是要做的。

**Comment by PeratX** [comment]
好的

**Comment by PeratX** [comment]
能具体下是传入还是传出？传入的话是直接Text形式，不用做解析把，发出的话，emoji倒是可以转成表情，目前`mirai native`也是支持`[CQ:emoji]`的发送的

**Comment by mrhso** [comment]
> 能具体下是传入还是传出？传入的话是直接Text形式，不用做解析把，发出的话，emoji倒是可以转成表情，目前`mirai native`也是支持`[CQ:emoji]`的发送的

这两个事件是传入啊。关键是，虽然实际上没有用酷 Q 码的必要，但是考虑到与酷 Q 一致还是需要转义。
