### ISSUE TITLE
易语言 JSON清空 卡加载

### ISSUE THREAD

**Issue by joyrhyme** [iTXTech/mirai-native#46]
使用精易模块编写的酷Q插件,只要涉及JSON清空都会在加载时卡住.
易语言5.8+精易模块8.3.5+mirai-native+miraiOK

**Comment by PeratX** [comment]
什么是json清空
请给出具体代码
据我所知 精易模块7.7.5之后的JSON全都是buggy的

**Comment by joyrhyme** [comment]
[com.example.demo.zip](https://github.com/iTXTech/mirai-native/files/5087917/com.example.demo.zip)
代码已上传..单纯使用json解析也会这样..酷Q的SDK为CQP_SDK_V9_191009

**Comment by joyrhyme** [comment]
具体为,正常情况下miraiOK加载完后,在提示login的下方会提示已经加载了什么插件,输入login登录后即可正常使用..但现在情况为miraiOK提示login后没提示加载什么插件,输入login或任何指令均无反应

**Comment by PeratX** [comment]
收到，有空将会调查

**Comment by PeratX** [comment]
请使用局部变量，不要用全局变量

```
.版本 2

.子程序 report, 文本型
.局部变量 json, 类_json

返回 (到文本 (json.解析 (到文本 (#json文本))))

```
