### ISSUE TITLE
右键任务栏程序图标 不出菜单

### ISSUE THREAD

**Issue by liergazi** [iTXTech/mirai-native#48]
现在用1.8.4 是正常的 升级到1.8.5/1.8.6 就不行了

**Comment by PeratX** [comment]
没错，你需要删除`CQP.dll`才能正常加载`1.8.5`以上版本

**Comment by liergazi** [comment]
原来是这样 我尝试一下 谢谢

**Comment by liergazi** [comment]
尝试了一下 自动又下载了mirai-core-qqandroid-1.2.1.jar  也自动生成了CQP.dll

**Comment by liergazi** [comment]
右键任务栏也出了菜单 但是插件加载不出了

**Comment by PeratX** [comment]
目前mirai native还没发布支持mirai core 1.2.x的版本，请等待明天或者使用mirai core 1.1系列版本

**Comment by liergazi** [comment]
好，谢谢你

**Comment by PeratX** [comment]
最新消息：console 1.0-M2目前还有较多bug，所以`mirai native`会推迟发布

**Comment by liergazi** [comment]
了解

**Comment by PeratX** [comment]
> 了解

有能力的可以自行编译console修复bug，然后就可以搭配 `mirai native 1.9.0-rc`使用了

**Comment by liergazi** [comment]
好的 只不过我刚刚通过mirai的控制台窗口看到M2.jar的源地址 我试着访问下载结果是404(两个都) 。我自己又没啥能力 只好等待大佬们的编译结果了

**Comment by liergazi** [comment]
第一次用这个github 才知道要关闭问题 抱歉

**Comment by PeratX** [comment]
不客气，现在可以使用core 1.1.3

**Comment by liergazi** [comment]
嗯嗯 谢谢 麻烦了
