### ISSUE TITLE
兼容报错

### ISSUE THREAD

**Issue by xiaobaozi233** [iTXTech/mirai-native#49]
使用插件：
https://github.com/yomunsam/EVEMarketBot

错误信息：
[hs_err_pid8596.log](https://github.com/iTXTech/mirai-native/files/5101307/hs_err_pid8596.log)

麻烦查一下，谢谢！

**Comment by PeratX** [comment]
插件问题导致的崩溃，请将调试器附加到java进程调试

**Comment by PeratX** [comment]
问题是否得到解决？

**Comment by xiaobaozi233** [comment]
还没。。。不是开发者，正在下环境准备边学边研究了

**Comment by PeratX** [comment]
是否注意了该项目README中的步骤？第一次启动崩溃是正常现象。

**Comment by xiaobaozi233** [comment]
应该不是这个问题，这个插件昨天刚请那边作者导出的dll+json，可能是从酷Q移植过来有一些地方有问题。

**Comment by PeratX** [comment]
好的，调试过程中遇到问题可以在此跟进
