### ISSUE TITLE
酷Q插件不生成配置文件

### ISSUE THREAD

**Issue by ddaodan** [iTXTech/mirai-native#52]
加载的酷Q插件是有配置文件的
![image](https://user-images.githubusercontent.com/40017293/90860733-1fcbde80-e3bd-11ea-9bdf-212a7594f0d5.png)
但是载入之后这个配置文件不生成
![image](https://user-images.githubusercontent.com/40017293/90860818-4853d880-e3bd-11ea-8421-440a5c8b7efe.png)
![image](https://user-images.githubusercontent.com/40017293/90860765-2fe3be00-e3bd-11ea-9031-806d44fd1c7a.png)
我也不知道应该放在哪里

**Comment by PeratX** [comment]
这样放好之后请启动mirai，文件夹会自动生成的

**Comment by ddaodan** [comment]
> 这样放好之后请启动mirai，文件夹会自动生成的

mirai重启了，但是并没有生成

**Comment by PeratX** [comment]
请提交完整mirai日志

**Comment by ddaodan** [comment]
[15:24:19.3235] I MiraiOK 20200629.160938 running at windows-386
[15:24:19.3255] I 此程序以Affero GPL3.0协议发布，使用时请遵守协议
[15:24:19.3255] I 代码库: github.com/LXY1226/MiraiOK gitee.com/LXY1226/MiraiOK
[15:24:19.6386] I JRE: openjdk version "1.8.0_252"
[15:24:19.6406] I JRE: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
[15:24:19.6406] I JRE: OpenJDK Client VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
[15:24:19.6406] I 删除.lastupdate来在下次强制检查更新
[15:24:19.6406] I 启动Mirai...
Using proxy: null
You are running Mirai-Console-Wrapper under C:\Users\Administrator\Desktop\mirai
All additional libraries are located at C:\Users\Administrator\Desktop\mirai\libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Stay on current version.
Fetching Newest Console Version of Pure
Stay on current version.
Version check complete, starting Mirai
shadow-Protocol:C:\Users\Administrator\Desktop\mirai\content\mirai-core-qqandroid-1.1.3.jar
Console        :C:\Users\Administrator\Desktop\mirai\content\mirai-console-0.5.2.jar
Root           :C:\Users\Administrator\Desktop\mirai/
 15:24:20 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console now running under C:\Users\Administrator\Desktop\mirai
 15:24:20 [INFO] [Mirai 0.5.2 Pkmon] Get news in github: https://github.com/mamoe/mirai
 15:24:20 [INFO] [Mirai 0.5.2 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 15:24:20 [INFO] [Mirai 0.5.2 Pkmon] Powered by Mamoe Technologies and contributors
 15:24:20 [INFO] [Plugin Manager] 开始加载C:\Users\Administrator\Desktop\mirai/plugins/下的插件
 15:24:20 [INFO] [Plugin Manager] loading plugin MiraiAPIHTTP
 15:24:21 [INFO] [Plugin Manager] successfully loaded plugin MiraiAPIHTTP version v1.7.3 by ryoii
 15:24:21 [INFO] [Plugin Manager] Mirai HTTP API Server Plugin
 15:24:21 [INFO] [Plugin Manager] loading plugin ConsoleAddition
 15:24:21 [INFO] [Plugin Manager] successfully loaded plugin ConsoleAddition version V0.2.3 by ryoii
 15:24:21 [INFO] [Plugin Manager] Mirai-console的增强插件，添加若干常用的命令
 15:24:21 [INFO] [Plugin Manager] loading plugin MiraiNative
 15:24:21 [INFO] [Plugin Manager] successfully loaded plugin MiraiNative version 1.8.6 by iTX Technologies
 15:24:21 [INFO] [Plugin Manager] 强大的 Mirai 原生插件加载器
 15:24:21 [INFO] [MiraiAPIHTTP] Loading Mirai HTTP API plugin
 15:24:21 [INFO] [MiraiAPIHTTP] Trying to Start Mirai HTTP Server in 0.0.0.0:8080
 15:24:21 [INFO] [ConsoleAddition] 1274634115
 15:24:21 [INFO] [ConsoleAddition] 读取了1个bot信息
 15:24:21 [INFO] [MiraiAPIHTTP] Starting Mirai HTTP Server in 0.0.0.0:8080
2020-08-21 15:24:21 I/Mirai HTTP API: Http api server is running with authKey: 1234567890
 15:24:21 [INFO] [MiraiAPIHTTP] 心跳模块启用状态: false
 15:24:21 [INFO] [MiraiAPIHTTP] 上报模块启用状态: false
 15:24:21 [INFO] [ConsoleAddition] 正在自动登录1274634115
 15:24:21 [INFO] [MiraiNative] 正在加载 C:\Users\Administrator\Desktop\mirai\plugins\MiraiNative\CQP.dll
 15:24:21 [INFO] [MiraiNative] 正在加载外部库 C:\Users\Administrator\Desktop\mirai\plugins\MiraiNative\libraries\libiconv.dll
 15:24:21 [INFO] [MiraiNative] 正在加载外部库 C:\Users\Administrator\Desktop\mirai\plugins\MiraiNative\libraries\sqlite3.dll
 15:24:21 [INFO] [Plugin Manager] 加载了3个插件
 15:24:21 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console 启动完成
 15:24:21 [INFO] [Mirai 0.5.2 Pkmon] "login qqnumber qqpassword " to login a bot
 15:24:21 [INFO] [Mirai 0.5.2 Pkmon] "login qq号 qq密码 " 来登录一个BOT
 15:24:21 [INFO] [MiraiNative] Native Plugin (w json) JustChat has been loaded with code 0
 15:24:22 [INFO] [ConsoleAddition] [Bot md5 Login] login...
 15:24:22 [INFO] [ConsoleAddition] [BOT 1274634115] Logging in...
 15:24:22 [INFO] [ConsoleAddition] [NETWORK] Connected to server 114.221.148.59:14000
 15:24:22 [INFO] [ConsoleAddition] [NETWORK] Send: wtlogin.login
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: LoginPacketResponse.Success
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Login successful
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: StatSvc.register
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: Response(StatSvc.register)
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] 开始加载好友信息
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] 开始加载群组列表与群成员列表
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.getFriendGroupList
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopListReqV2
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetFriendGroupList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetFriendGroupList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] 正在加载好友列表 41/41
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] 好友列表加载完成, 共 41个
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: OidbSvc.0x88d_7
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Send: friendlist.GetTroopMemberListReq
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Recv: FriendList.GetTroopMemberList.Response
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] 群组列表与群成员加载完成, 共 14个
 15:24:23 [INFO] [ConsoleAddition] [NETWORK] Syncing friend message history...
 15:24:24 [INFO] [ConsoleAddition] [NETWORK] Awaiting ConfigPushSvc.PushReq
 15:24:24 [INFO] [ConsoleAddition] [NETWORK] Send: MessageSvc.PbGetMsg
 15:24:24 [INFO] [ConsoleAddition] [NETWORK] Send: MessageSvc.PbDeleteMsg
 15:24:24 [INFO] [ConsoleAddition] [NETWORK] unknown PbGetMsg type 528, data=08 4E 12 3F 08 EC 90 F7 FF 01 10 EC 90 F7 FF 01 18 17 22 2F 0A 2D 0A 20 36 63 63 38 66 64 31 66 30 30 30 30 30 30 30 30 38 37 37 35 33 66 35 66 36 33 30 63 30 61 30 30 10 DC C6 FE DC 02 1D 87 75 3F 5F
 15:24:24 [INFO] [ConsoleAddition] [NETWORK] Syncing friend message history: Success
 15:24:24 [INFO] [MiraiNative] Mirai Native 正启用所有插件。
 15:24:24 [INFO] [ConsoleAddition] [BOT 1274634115] Login successful
 15:24:24 [INFO] [Command] 1274634115 login successes
 15:24:24 [INFO] [ConsoleAddition] 1274634115 自动登录成功
 15:24:26 [INFO] [ConsoleAddition] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 15:24:26 [INFO] [ConsoleAddition] [NETWORK] Send: ConfigPushSvc.PushResp
 15:24:26 [INFO] [ConsoleAddition] [NETWORK] ConfigPushSvc.PushReq: Success
 15:24:26 [INFO] [ConsoleAddition] [NETWORK] Received unknown commandName: ConfigPushSvc.PushDomain
 15:24:26 [INFO] [ConsoleAddition] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 15:24:26 [INFO] [ConsoleAddition] [NETWORK] Send: ConfigPushSvc.PushResp
 15:24:50 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush
你配吗list 15:24:58 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush                              npm
 15:25:04 [INFO] [Bot Login] login...
 15:25:04 [INFO] [BOT 1274634115] Logging in...
 15:25:04 [INFO] [NETWORK] Connected to server msfwifi.3g.qq.com:8080
 15:25:04 [INFO] [NETWORK] Send: wtlogin.login
 15:25:04 [INFO] [NETWORK] Recv: Error(title=登录失败, message=帐号或密码错误，请重新输入。, errorInfo=)
 15:25:04 [INFO] [Command] 1274634115 login failed -> Error(title=登录失败, message=帐号或密码错误，请重新输入。, errorInfo=)
npm list
 15:25:11 [INFO] [Command] 共加载了 1 个 Mirai Native 插件
Id：0 标识符：com.superexercisebook.justchat 名称：JustChat 版本：2.0.1 状态：已启用 已加载
 15:25:23 [INFO] [ConsoleAddition] [NETWORK] Send: Heartbeat.Alive
 15:25:23 [INFO] [ConsoleAddition] [NETWORK] Recv: Heartbeat.Alive.Response
 15:25:53 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush
 15:26:02 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush
 15:26:23 [INFO] [ConsoleAddition] [NETWORK] Send: Heartbeat.Alive
 15:26:23 [INFO] [ConsoleAddition] [NETWORK] Recv: Heartbeat.Alive.Response
 15:26:57 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush
 15:27:06 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush
 15:27:23 [INFO] [ConsoleAddition] [NETWORK] Send: Heartbeat.Alive
 15:27:23 [INFO] [ConsoleAddition] [NETWORK] Recv: Heartbeat.Alive.Response
 15:28:00 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush
 15:28:09 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush
 15:28:23 [INFO] [ConsoleAddition] [NETWORK] Send: Heartbeat.Alive
 15:28:23 [INFO] [ConsoleAddition] [NETWORK] Recv: Heartbeat.Alive.Response

**Comment by PeratX** [comment]
那你可能需要手动新建文件夹 `MiraiNative/data/插件包名/config.json`

**Comment by ddaodan** [comment]
> 那你可能需要手动新建文件夹 `MiraiNative/data/插件包名/config.json`

感谢，插件可以识别了
