### ISSUE TITLE
mirai-console-1.0-M2-1-all 配 mirai-native-1.9.0-rc.2 报main方法错误

### ISSUE THREAD

**Issue by m839336369** [iTXTech/mirai-native#61]
# 警告：请认真填写以下栏目，如果不符合要求，将直接被关闭。编辑完请删除此行。

**描述这个Bug**
清晰准确地表述这个Bug。
昨天还配置的，今天换了台电脑就不能用了，有点懵。

**复现步骤**

**期望的行为**
清晰准确地描述您期望的行为。

**截图和日志**
您必须提交相应的截图和 mirai console 日志
![image](https://user-images.githubusercontent.com/30934916/91014670-6408ea00-e61c-11ea-81f9-334d11baf10b.png)

**运行环境**
 - 操作系统：WIN10
 - `mirai core` 版本：mirai-core-qqandroid-1.2.2
 - `mirai console` 版本：mirai-console-1.0-M2-1-all
 - `mirai native` 版本：mirai-native-1.9.0-rc.2
 - `Java` 运行时版本：32

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
可能是jar损坏了

**Comment by m839336369** [comment]
> 可能是jar损坏了

考虑过，刚刚还从你的relase中重新下载了一遍，依旧，你那里可以么？

**Comment by PeratX** [comment]
我可以

**Comment by m839336369** [comment]
> hmmm，不排除是console的问题，但我没有idea，你能发一下mirai三件套嘛O(∩_∩)O

**Comment by PeratX** [comment]
我建议你换个文件夹名字
![image](https://user-images.githubusercontent.com/13656668/91018187-da5c1b00-e621-11ea-98f4-88bfe9f84117.png)

**Comment by m839336369** [comment]
> 我建议你换个文件夹名字
> ![image](https://user-images.githubusercontent.com/13656668/91018187-da5c1b00-e621-11ea-98f4-88bfe9f84117.png)
确定了，文件夹不能包含空格
