### ISSUE TITLE
收到表情消息cmd窗口显示问号＆附加程序调试应该附加到哪里

### ISSUE THREAD

**Issue by m839336369** [iTXTech/mirai-native#62]
# 警告：请认真填写以下栏目，如果不符合要求，将直接被关闭。编辑完请删除此行。

**描述这个Bug**
清晰准确地表述这个Bug。

**复现步骤**

**期望的行为**
清晰准确地描述您期望的行为。

**截图和日志**
您必须提交相应的截图和 mirai console 日志

**运行环境**
 - 操作系统：[例子：Windows 10 2004]
 - `mirai core` 版本：[例子：1.2.1]
 - `mirai console` 版本：[例子：1.0]
 - `mirai native` 版本：[例子：1.9.0]
 - `Java` 运行时版本：[例子：11.0.7 x86]

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
如果控制台不支持UTF-8将会是问号，这是正常情况。调试器直接附加到`java.exe`进程调试
