### ISSUE TITLE
a fatal error has been detected by the java runtime environment

### ISSUE THREAD

**Issue by RedShameA** [iTXTech/mirai-native#64]
**描述这个Bug**
运行中出现这个报错

**复现步骤**
无

**期望的行为**
修复报错

**截图和日志**
https://i.loli.net/2020/08/25/tvhD4s6fu7dETNV.png

**运行环境**
 - 操作系统：winserver2019
 - `mirai core` 版本： 1.0-M2-1
 - `mirai console` 版本：Pure: version 1.0-M2-1
 - `mirai native` 版本：1.9.0 RC2
 - `Java` 运行时版本：java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) Client VM (build 25.261-b12, mixed mode)

**更多信息**
文件发在下面

**Comment by RedShameA** [comment]
另一个文件太大了，需要的话我再发吧

https://github.com/RedShameA/baocuo

**Comment by PeratX** [comment]
必须填写复现步骤，无法修复无法复现的报错

**Comment by RedShameA** [comment]
> 必须填写复现步骤，无法修复无法复现的报错

你先看一下log，我在找复现方法

**Comment by PeratX** [comment]
log看了，确实是位于`CQP.dll`，现在需要复现方法

**Comment by PeratX** [comment]
可以尝试添加启动参数`-Xchech:jni` 获得更多信息

**Comment by RedShameA** [comment]
> log看了，确实是位于`CQP.dll`，现在需要复现方法

我找到了，是用到插件的某个功能就会报错，我想办法定位一下具体是什么导致报错

**Comment by RedShameA** [comment]
> 可以尝试添加启动参数`-Xchech:jni` 获得更多信息

启动mirai的时候加上吗

**Comment by PeratX** [comment]
> > 可以尝试添加启动参数`-Xchech:jni` 获得更多信息
> 
> 启动mirai的时候加上吗

是的，而且可能的话，上传`C:\Program Files (x86)\Common Files\Oracle\Java\javapath\hs_err_pid9016.mdmp`

**Comment by RedShameA** [comment]
> > > 可以尝试添加启动参数`-Xchech:jni` 获得更多信息
> > 
> > 
> > 启动mirai的时候加上吗
> 
> 是的，而且可能的话，上传`C:\Program Files (x86)\Common Files\Oracle\Java\javapath\hs_err_pid9016.mdmp`

https://reda.lanzous.com/iNm4Ng1o9oj刚才的给删了，这是重现的报错文件

**Comment by PeratX** [comment]
能否配合我调试？我发你个修改过的CQP.dll，你替换一下

**Comment by PeratX** [comment]
直接替换MiraiNative中同名文件
[CQP.zip](https://github.com/iTXTech/mirai-native/files/5123379/CQP.zip)

**Comment by RedShameA** [comment]
> 能否配合我调试？我发你个修改过的CQP.dll，你替换一下
> 
> 

可以，你发来。我测试后回你

**Comment by PeratX** [comment]
看了一下，应该是收到私聊之后发送了一条群聊消息然后就崩溃了

**Comment by RedShameA** [comment]
> 看了一下，应该是收到私聊之后发送了一条群聊消息然后就崩溃了

对，我也在定位错误，是在类中发送到群空消息崩溃。还没测试完

**Comment by RedShameA** [comment]
> 看了一下，应该是收到私聊之后发送了一条群聊消息然后就崩溃了

出现灵异事件了...

有一个类的子程序是把一段文本处理一下发送到群里。
如果传入空文本的话发送就会报错；我在这个子程序内在要发送的代码前边把储存文本的变量赋值为空文本，继续发送就是普通的mirai报empty了

我还在发送的前边将处理过的文本和空文本进行比较，是相同的...

**Comment by PeratX** [comment]
我对发送空消息做个特殊处理试试

**Comment by RedShameA** [comment]
> 直接替换MiraiNative中同名文件
> [CQP.zip](https://github.com/iTXTech/mirai-native/files/5123379/CQP.zip)

啊刚看见这个...我去测试一下

**Comment by RedShameA** [comment]
> > 直接替换MiraiNative中同名文件
> > [CQP.zip](https://github.com/iTXTech/mirai-native/files/5123379/CQP.zip)
> 
> 啊刚看见这个...我去测试一下

这个还是报同样错误了

**Comment by PeratX** [comment]
必然报同样的错误，但是报错之前应该会打印一行

**Comment by RedShameA** [comment]
> 必然报同样的错误，但是报错之前应该会打印一行

并没有多打印一行

**Comment by RedShameA** [comment]
<img src="https://i.loli.net/2020/08/25/boFs7LAQl1YPIft.png">

**Comment by PeratX** [comment]
已复现并修复，发送`null`文本会导致崩溃，下个版本即将发布（与`mirai console 1.0-M3`同步)

**Comment by RedShameA** [comment]
> 已复现并修复，发送`null`文本会导致崩溃，下个版本即将发布（与`mirai console 1.0-M3`同步)

有没有编译好的，可以让我来测试一下 嘻嘻

**Comment by PeratX** [comment]
> > 已复现并修复，发送`null`文本会导致崩溃，下个版本即将发布（与`mirai console 1.0-M3`同步)
> 
> 有没有编译好的，可以让我来测试一下 嘻嘻

直接下载仓库中的CQP.dll即可

**Comment by RedShameA** [comment]
> > > 已复现并修复，发送`null`文本会导致崩溃，下个版本即将发布（与`mirai console 1.0-M3`同步)
> > 
> > 
> > 有没有编译好的，可以让我来测试一下 嘻嘻
> 
> 直接下载仓库中的CQP.dll即可

好的谢谢

**Comment by RedShameA** [comment]
> > > 已复现并修复，发送`null`文本会导致崩溃，下个版本即将发布（与`mirai console 1.0-M3`同步)
> > 
> > 
> > 有没有编译好的，可以让我来测试一下 嘻嘻
> 
> 直接下载仓库中的CQP.dll即可

很不幸，还是报错了......

**Comment by PeratX** [comment]
> > > > 已复现并修复，发送`null`文本会导致崩溃，下个版本即将发布（与`mirai console 1.0-M3`同步)
> > > 
> > > 
> > > 有没有编译好的，可以让我来测试一下 嘻嘻
> > 
> > 
> > 直接下载仓库中的CQP.dll即可
> 
> 很不幸，还是报错了......

我测试已经ok了，你那边我就不知道了

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/91272078-c0e7da00-e7ad-11ea-89b6-1a9c35fe3a9e.png)
报错是肯定的，但是不会崩溃

**Comment by RedShameA** [comment]
> > > > > 已复现并修复，发送`null`文本会导致崩溃，下个版本即将发布（与`mirai console 1.0-M3`同步)
> > > > 
> > > > 
> > > > 有没有编译好的，可以让我来测试一下 嘻嘻
> > > 
> > > 
> > > 直接下载仓库中的CQP.dll即可
> > 
> > 
> > 很不幸，还是报错了......
> 
> 我测试已经ok了，你那边我就不知道了



> ![image](https://user-images.githubusercontent.com/13656668/91272078-c0e7da00-e7ad-11ea-89b6-1a9c35fe3a9e.png)
> 报错是肯定的，但是不会崩溃

我是和昨天相同的报错(崩溃)
我在想办法把报错代码复现一份发你

**Comment by PeratX** [comment]
是不是这个文件 https://github.com/iTXTech/mirai-native/blob/master/src/main/resources/CQP.dll

**Comment by RedShameA** [comment]
> 是不是这个文件 https://github.com/iTXTech/mirai-native/blob/master/src/main/resources/CQP.dll

敖，是我把dll文件搞错了，抱歉...

**Comment by PeratX** [comment]
不是，还有其他的DLL？

**Comment by RedShameA** [comment]
> 不是，还有其他的DLL？

昨天发的这个

> 直接替换MiraiNative中同名文件
> [CQP.zip](https://github.com/iTXTech/mirai-native/files/5123379/CQP.zip)

被我解压在了下载目录，新下载的成了CQP-2.dll

是我的问题...提问前要先确保不会出现这种错误

**Comment by PeratX** [comment]
所以现在可以了吗

**Comment by RedShameA** [comment]
> 所以现在可以了吗

现在可以了。
只替换了CQP.dll
重新进行报错操作，现在提示empty不会退出了
谢谢开发者

**Comment by PeratX** [comment]
> > 所以现在可以了吗
> 
> 现在可以了。
> 只替换了CQP.dll
> 重新进行报错操作，现在提示empty不会退出了
> 谢谢开发者

这是正常的
