### ISSUE TITLE
有没人发布编译好的完整包呢？

### ISSUE THREAD

**Issue by ssdoufu** [iTXTech/mirai-native#65]
# 警告：请认真填写以下栏目，如果不符合要求，将直接被关闭。编辑完请删除此行。

**特性描述**
如标题。有没人发布编译好的完整包，目前只会易语言，源码不知道用什么工具编译！！

**Comment by PeratX** [comment]
可以在[Releases](https://github.com/iTXTech/mirai-native/releases)下载
