### ISSUE TITLE
关于CQ码的支持

### ISSUE THREAD

**Issue by AdorableParker** [iTXTech/mirai-native#66]
新版的音乐分享卡片消息解析不了
相关log：
> `[ERROR] [MiraiNative] CQ消息解析失败：[CQ:rich,data={"app":"com.tencent.structmsg","config":{"autosize":true, "ctime": 1598434373, "forward": true, "token": "50d008a28f3fb8176919bebf454f6370", "type": "normal" }, "desc": "音乐", "meta": { "music": { "action": "", "android_pkg_name": "", "app_type": 1, "appid": 100497308, "desc": "後ろから這いより隊G", "jumpUrl": "https://i.y.qq.com/v8/playsong.html?platform=11&appshare=android_qq&appversion=10030010&hosteuin=oK457ecFoeEsNv**&songmid=001Q6TYt2CcoXm&type=0&appsongtype=1&_wv=1&source=qq&ADTAG=qfshare", "musicUrl": "http://c6.y.qq.com/rsc/fcgi-bin/fcg_pyq_play.fcg?songid=&songmid=001Q6TYt2CcoXm&songtype=1&fromtag=50&uin=1514880969&code=4A9FE", "preview": "http://y.gtimg.cn/music/photo_new/T002R150x150M000004OiyIC1py0fr_1.jpg", "sourceMsgId": "0", "source_icon": "", "source_url": "", "tag": "QQ音乐", "title": "太陽曰く燃えよカオス (太阳说燃烧吧混沌) (ニャル ラ..." } }, "prompt": "[分享]太陽曰く燃えよカオス (太阳说燃烧吧混沌) (ニャルラ...", "ver": "0.0.0.1", "view": "music" }]`
---
native支持发mirai码吗

**Comment by PeratX** [comment]
不支持发送mirai码，CQ码内部未经转码，请认真阅读文档。不按照格式发issue直接关闭。
