### ISSUE TITLE
Fail to receive private msg

### ISSUE THREAD

**Issue by yar2001** [iTXTech/mirai-native#70]
**描述这个Bug**
部分成员私聊信息接收不到，但部分成员私聊消息可以接收的到。猜测是QQ号码位数较长则接收不到。
但所有成员的群消息均可以接收到。
使用的CQ插件在酷Q运行时没有问题。

**复现步骤**
部分成员进行私聊，则会出现这个问题。

**截图和日志**
控制台输出中似乎没有显示私聊信息。

**运行环境**
 - 操作系统：Windows 10 Latest Version
 - `mirai core` 版本：1.2.1
 - `mirai console` 版本：1.3.0
 - `mirai native` 版本：1.8.6
 - `Java` 运行时版本：8.0.2520 x64

**Comment by PeratX** [comment]
请向mirai汇报该问题。
