### ISSUE TITLE
在config.txt中加login自动登录后，MiraiNative插件不能自动启用

### ISSUE THREAD

**Issue by nlpguyz** [iTXTech/mirai-native#71]
**描述这个Bug**
如果不在config.txt自动登录，而是手动从控制台输入login命令，MiraiNative的插件可以自动启用（在config.json中enable即可）。但是，如果是config.txt自动登录的，在完全初始化好之后，MiraiNative载入的插件都是禁用的。需要在login完全完成后，打npm enable 0才能启用。

**复现步骤**
1. 安装MiraiNative插件，并在plugins中放一个酷Q的插件，并且在config.json中设置启用"enable"
2. 启动 mirai-console (我用的是miraiok)，输入 login <qq> <password> 登录，等待加载各种好友和群信息，直到能看到接收的消息，打 npm list 查看插件状态，为启用。
3. 修改config.txt加入login <qq> <password>
4. 重新启动mirai，在自动登录完成，看到消息后，打 npm list 看到插件被禁用了。需要输入 npm enable 0 才能启用插件。

**期望的行为**
启动后，npm list 看到插件处于启用状态。

**截图和日志**
![image](https://user-images.githubusercontent.com/25698072/91634225-9fe8da00-e9a3-11ea-87fb-bfd27f4e357e.png)

**运行环境**
 - 操作系统：[例子：Windows 10 2004]
 - `mirai core` 版本：[1.0]
 - `mirai console` 版本：[1.0]
 - `mirai native` 版本：[1.9.0]
 - `Java` 运行时版本：[9.0 x86]

**Comment by PeratX** [comment]
`config.txt`是哪个程序的？

**Comment by Pika-Lee** [comment]
> `config.txt`是哪个程序的？

那个是1.8.X包里自带的，配合mirai_ok.exe可以实现mirai加载后自动登陆（读取了config.txt中写好的login指令然后在cmd中执行）。
![config](https://user-images.githubusercontent.com/23114990/91937844-69a1b680-ed25-11ea-926a-0b04c076ccac.png)

不过1.9.0好像不支持mirai_ok和autologin了，听说接下来发布的M4可能才会支持。

**Comment by Pika-Lee** [comment]
根据楼主的描述，用的应该是1.8.X版本的native，我之前手动加载dll的时候，也是会默认禁用插件，需要手动启用（[#37](https://github.com/iTXTech/mirai-native/issues/37#issuecomment-679011390)）。分享一个自己之前用过的临时解决办法： 在config.txt末尾的login指令后面敲十几个回车（延迟等待），然后加一条npm enable 0，这样就可以实现登陆后自动启用插件了。

**Comment by PeratX** [comment]
这个bug应该1.9早修复了才对

**Comment by Pika-Lee** [comment]
不清楚，我是没出现过这个问题（1.9没遇到过，之前用的1.8.X也没遇到），可能是楼主插件本身，或者mirai环境配置的问题吧。

**Comment by PeratX** [comment]
楼主至今没能提供更多信息，今天24点前如果还没提供更多信息，将暂时关闭此issue
