### ISSUE TITLE
将通过菜单载入的窗口移动到独立线程中

### ISSUE THREAD

**Issue by RedShameA** [iTXTech/mirai-native#75]
**描述这个Bug**
在打开插件设置窗口时，插件会暂停处理消息
以启动线程方式打开窗口不会出现暂停

与[#25](https://github.com/iTXTech/mirai-native/issues/25)最后反馈的问题相同

**复现步骤**
点出插件设置窗口，即会暂停处理消息

**期望的行为**
点出插件设置窗口，仍可处理消息

**截图和日志**
无

**运行环境**
 - 操作系统：winserver 2019
 - `mirai core` 版本：1.2.2
 - `mirai console` 版本：1.0m2
 - `mirai native` 版本：1.9.0rc2
 - `Java` 运行时版本：11.0.7 x86

**更多信息**
这个也不知道该不该反馈，好像是一个无关大雅的问题
所以开发者可以关闭这个反馈不必对此修复

**Comment by PeratX** [comment]
已知问题，一直想优化，最近搞一下。
