### ISSUE TITLE
多次取群成员列表数据不会刷新

### ISSUE THREAD

**Issue by MrTC1277** [iTXTech/mirai-native#77]
**描述这个Bug**
第一次取群成员列表没有问题，即使进行了修改，之后的数据与第一次相同，

**复现步骤**
发送指令触发取群成员列表
**期望的行为**
每次取群成员列表都可以是刷新的数据

**截图和日志**
![QQ截图20200823233756](https://user-images.githubusercontent.com/37472014/91725354-31895f00-ebd1-11ea-8382-b1d9c53233c4.png)
![QQ截图20200831212759](https://user-images.githubusercontent.com/37472014/91725366-377f4000-ebd1-11ea-9e93-3ecc1b0e0bff.png)

**运行环境**
 - 操作系统：Windows 10 1909
 - `mirai core` 版本：：1.2.2
 - `mirai console` 版本：1.0-M3-1
 - `mirai native` 版本：1.9.0
 - `Java` 运行时版本：1.8.0_252 x86

**Comment by MrTC1277** [comment]
这里在提一个建议，希望每次机器人进行一些操作后能返回操作结果，比如设置群名片，设置成功返回真

**Comment by PeratX** [comment]
`mirai native`不对群成员列表缓存，请向`mirai`汇报该问题。

**Comment by PeratX** [comment]
> 这里在提一个建议，希望每次机器人进行一些操作后能返回操作结果，比如设置群名片，设置成功返回真

`mirai native`内部采用非阻塞实现，如果阻塞将会显著延长事件处理时间
