### ISSUE TITLE
多次接收同一图片时只创建一个文件

### ISSUE THREAD

**Issue by RedShameA** [iTXTech/mirai-native#79]
**特性描述**
如：

a私聊发送：[mirai:source:28906,15072][mirai:image:/1573636056-587011059-BBBCF540EF99C9F6C5841717A7E686D1]
a在群发送：[mirai:image:{BBBCF540-EF99-C9F6-C584-1717A7E686D1}.mirai]

b私聊发送：[mirai:source:16698,45664][mirai:image:/2244752581-491024462-BBBCF540EF99C9F6C5841717A7E686D1]
b在群发送：[mirai:image:{BBBCF540-EF99-C9F6-C584-1717A7E686D1}.mirai]

可以发现这些都一同一图片，现在是会分别不同名字保存，希望可以只保存一个

**Comment by PeratX** [comment]
这个是`mirai`的机制，请向`mirai`反馈
