### ISSUE TITLE
一系列 CQ 码的支援

### ISSUE THREAD

**Issue by mrhso** [iTXTech/mirai-native#8]
我在 CoolQ Socket API 的 Node.js 部分举了（所发现的）CQ 码的实例，可以作为完善 CQ 码处理的参考。
https://github.com/mrhso/cqsocketapi/blob/master/QQBot.js#L416

**Comment by PeratX** [comment]
收到，将会查阅

**Comment by PeratX** [comment]
mirai支持的已经全部添加，部分类型不兼容的请以mirai为准。
