### ISSUE TITLE
[CQ:image,url=xxxx]发送图片不显示，为裂图

### ISSUE THREAD

**Issue by m839336369** [iTXTech/mirai-native#80]
**描述这个Bug**
[CQ:image,url=xxxx]发送图片不显示，为裂图，图片成功发出，cmd后台显示[mirai:image]应该是识别了，在QQ那里则是显示图片裂图，使用url的地址正确（http.xxxxx.jpg），请问是需要加什么尾缀么？

**复现步骤**

**期望的行为**
清晰准确地描述您期望的行为。

**截图和日志**
您必须提交相应的截图和 mirai console 日志

**运行环境**
 - 操作系统：[例子：Windows 10 2004]
 - `mirai core` 版本：[例子：1.2.1]
 - `mirai console` 版本：[例子：1.0]
 - `mirai native` 版本：[例子：1.9.0]
 - `Java` 运行时版本：[例子：11.0.7 x86]

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
来个链接

**Comment by m839336369** [comment]
> 
> 
> 来个链接

[CQ:image,url=http://linda.ronsir.com/files/base/rid6861/839336369_1599045451530.png]

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/92108519-1bbaaa80-ee1a-11ea-82c4-dcc2ce6de2fa.png)
测试可以成功发送

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/92108625-43117780-ee1a-11ea-8451-d12af4e2623e.png)

**Comment by Pika-Lee** [comment]
裂图有可能也是接收端的问题，楼主可以试试点击裂图刷新试试，看看能否恢复显示。
