### ISSUE TITLE
mirai native发送消息时报错：无法找到群

### ISSUE THREAD

**Issue by Pika-Lee** [iTXTech/mirai-native#81]
**描述这个Bug**
①mirai运行一段时间后无法发送群/私聊消息，提示“**无法找到群：XXXXX**”（奇怪的是，这里的XXXX不是群号而是上一条消息的QQ号。见下文日志截图）
②有时候虽然console的日志中已经显示了插件的处理后（发送）的消息，但是群内/私聊并没有正常收到（重启mirai后恢复正常）
③（小概率偶现）mirai运行一段时间后console控制台日志流卡死（阻塞），按下回车后日志恢复到最新位置（消息恢复处理）

**复现步骤**
暂未观察到明显复现规律，上一次出现是在高峰时段（0点），推测可能和短时间内出现大量待处理消息有关。

**期望的行为**
mirai能提高运行的稳定性

**截图和日志**
![bug](https://user-images.githubusercontent.com/23114990/92008344-a26b7b00-ed79-11ea-88c6-80cee2e9cbe9.png)
![error2](https://user-images.githubusercontent.com/23114990/92008346-a26b7b00-ed79-11ea-9aef-d15ebb559166.png)
![error3](https://user-images.githubusercontent.com/23114990/92008347-a3041180-ed79-11ea-8704-75dc0e7862a4.png)

**运行环境**
 - 操作系统：[例子：Windows Server 2016]
 - `mirai core` 版本：[例子：1.2.2]
 - `mirai console` 版本：[例子：1.0]
 - `mirai native` 版本：[例子：1.9.0-M3-1]
 - `Java` 运行时版本：[例子：1.8.0 252]

**更多信息**
希望1.9.0以后版本能增加一个autologin的配置，以便利用定时重启策略来减少崩溃带来的影响。

**Comment by PeratX** [comment]
autologin应该是`mirai`的功能，而非`mirai native`的功能。
`日志流卡死`的情况请确认关闭了快速选择功能。

**Comment by PeratX** [comment]
`无法找到群`只会在发送`at`时提示，请问是否在私聊中发送了`at`？

**Comment by Pika-Lee** [comment]
> `无法找到群`只会在发送`at`时提示，请问是否在私聊中发送了`at`？

我刚才定位了一下，“无法找到群”的这个问题应该是和一个签到插件有关，这个插件检测到群友每天第一次群内发言时，会自动对该QQ**私聊**发送一条签到成功的消息。这条私聊消息中确实有使用到**at**，不知道是不是由于这个原因导致的？

**Comment by PeratX** [comment]
是的，这个只是提示，不会有实际错误，会自动忽略at

**Comment by Pika-Lee** [comment]
> 是的，这个只是提示，不会有实际错误，会自动忽略at

但有时好像也不能正常发送私聊消息，似乎和**长度**有关，超过一定长度后就无法私聊发送了？

比如我刚才测试了一条稍微有点长的消息（412字），群聊就能正常发送，私聊就会报错。
![111](https://user-images.githubusercontent.com/23114990/92014803-6688e380-ed82-11ea-9013-fdfc0260d750.png)
![222](https://user-images.githubusercontent.com/23114990/92014809-67ba1080-ed82-11ea-9d83-2798f4bf3673.png)

**Comment by PeratX** [comment]
`mirai`暂不支持私聊长消息，请认真阅读`mirai`的README文件
