### ISSUE TITLE
1.9.0插件新生成的图片无法正常发送

### ISSUE THREAD

**Issue by Pika-Lee** [iTXTech/mirai-native#82]
**描述这个Bug**
更新1.9.0后，CQ插件加载后**新生成**（如从网络下载获取）的图片还是会存放在 \jre\bin\data\image，但由于1.9.0目录结构的改变，只有在data\image中的图片才能够正常发送。因此这类插件将**无法正常发送图片**。

**复现步骤**
1.某插件从网上抓取了一张图片，默认保存在 \jre\bin\data\image目录下
2.mirai发送消息时，由于目录结构改变，只能从data\image读取图片，返回空
3.机器人发出的消息不带图片

**期望的行为**
mirai native能够兼容此类插件，使其在旧目录下生成的图片也能够正常发送。

**截图和日志**
![QQ截图20200903163616](https://user-images.githubusercontent.com/23114990/92092207-5dd8f180-ee04-11ea-8c6f-548f940510ea.png)

**运行环境**
 - 操作系统：[例子：Windows Server 2016]
 - `mirai core` 版本：[例子：1.2.2]
 - `mirai console` 版本：[例子：1.0]
 - `mirai native` 版本：[例子：1.9.0-M3-1]
 - `Java` 运行时版本：[例子：1.8.0 252]

**更多信息**
希望native能兼容一下旧图片位置，有些CQ插件已经停止维护了，插件本身难以通过修改代码来解决图片生成位置的问题，麻烦mirai能适配一下这类插件。

**Comment by PeratX** [comment]
确认用的是`mirai native 1.9.0`而非`rc`版本吗？从`1.9.0`正式版本开始，会强制设定插件的运行目录到本目录，如果无法使用，请替换稍后上传的`CQP.dll`帮助我们测试

**Comment by Pika-Lee** [comment]
> 确认用的是`mirai native 1.9.0`而非`rc`版本吗？从`1.9.0`正式版本开始，会强制设定插件的运行目录到本目录，如果无法使用，请替换稍后上传的`CQP.dll`帮助我们测试

确认，我用的是正式版，不是rc

**Comment by PeratX** [comment]
好的，请您替换`CQP.dll`到`MiraiConsole\data\MiraiNative`，不需要理会启动时的警告。
[CQP.zip](https://github.com/iTXTech/mirai-native/files/5167545/CQP.zip)

**Comment by Pika-Lee** [comment]
> 好的，请您替换`CQP.dll`到`MiraiConsole\data\MiraiNative`，不需要理会启动时的警告。
> [CQP.zip](https://github.com/iTXTech/mirai-native/files/5167545/CQP.zip)

替换了之后还是不出图，插件生成的图片还是位于 \jre\bin\data\image
![222](https://user-images.githubusercontent.com/23114990/92099068-a399b800-ee0c-11ea-8f89-a841cc019018.png)

**Comment by PeratX** [comment]
还是易语言的问题，`krnl.fne`里面会修改目录

**Comment by Pika-Lee** [comment]
> 还是易语言的问题，`krnl.fne`里面会修改目录

emm好像不只是语言的问题，另外一个插件不是用易语言写的，也出现了同样发的问题。

我刚才问了一下那个插件作者，他说是和取目录地址的写法有关，和语言无关。他直接取的是根目录（CQ根目录-->\jre\bin\）下的/data文件夹，但生成的图片还是位于 \jre\bin\data\image。（他的插件不是用易语言写的）

**Comment by PeratX** [comment]
`取目录`不知道指的是什么，易语言载入插件时候会强制调用`SetCurrentDirectory`改变运行目录到exe所在位置，`mirai native`在加载之后也会调用`SetCurrentDirectory`设置正确的运行目录，但是易语言的`取运行目录`只会返回`exe`所在路径

**Comment by PeratX** [comment]
> > 还是易语言的问题，`krnl.fne`里面会修改目录
> 
> 图片中的那个插件确实是易语言写的，感谢修复。
> 
> 不过好像不只是易语言的问题，另外一个插件不是用易语言写的，也出现了同样的问题。
> 
> 我刚才问了一下那个插件作者，他说是和取目录地址的写法有关，和语言无关。他直接取的是根目录（CQ根目录-->\jre\bin\）下的/data文件夹，然后生成的图片还是位于 \jre\bin\data\image。（他的插件不是用易语言写的）
> 
> 那个插件作者可能比较忙，刚才我问他也没有和我解释太多，上面一段我大概转述了一下他说的意思。我的个人理解是在1.9.0环境下，他插件用到的**取目录**方法还是取到了\jre\bin\而没有取到新目录地址，所以导致了插件生成的图片无法正常发送。
> 
> 您看能不能这样？保持现有的策略不变（强制设定插件的运行目录到新目录），发送图片时默认取新目录data\image，如果找不到对应图片文件的话，再尝试从\jre\bin\data\image获取一次？

现在的修复已经保留了`jre`文件夹下的`data`目录，可能需要管理员权限

**Comment by Pika-Lee** [comment]
> `取目录`不知道指的是什么，易语言载入插件时候会强制调用`SetCurrentDirectory`改变运行目录到exe所在位置，`mirai native`在加载之后也会调用`SetCurrentDirectory`设置正确的运行目录，但是易语言的`取运行目录`只会返回`exe`所在路径

我看了一下截图中那个易语言插件的源码，eventStartup中有调用**CQ.取应用目录 ()** 
![111](https://user-images.githubusercontent.com/23114990/92112089-da2cfe00-ee1f-11ea-818c-8c89824a2727.png)

而涉及图片存储的代码有调用**取运行目录 ()**，这里应该取的是exe的运行目录（CQ根目录-->\jre\bin\），这样就和前文截图中的图片存储位置对上了。
![33333](https://user-images.githubusercontent.com/23114990/92112216-0b0d3300-ee20-11ea-8056-7099b817d7ae.png)

**Comment by PeratX** [comment]
取运行目录 () 是易语言一大败笔，官方从未想过要修改，一直有人提出。

**Comment by Pika-Lee** [comment]
刚才安装了新发布的1.9.1版native，旧目录的图片已经可以正常显示了，感谢。
> 
> 现在的修复已经保留了`jre`文件夹下的`data`目录，可能需要管理员权限
![bug](https://user-images.githubusercontent.com/23114990/92618494-013d7100-f2f3-11ea-863c-b4891e5febbc.png)
不过还有点小问题，上图中的红色提示内容貌似每次启动mirai的时候都会弹出，无论是否以管理员的方式启动。

**Comment by PeratX** [comment]
> 刚才安装了新发布的1.9.1版native，旧目录的图片已经可以正常显示了，感谢。
> 
> > 现在的修复已经保留了`jre`文件夹下的`data`目录，可能需要管理员权限
> > ![bug](https://user-images.githubusercontent.com/23114990/92618494-013d7100-f2f3-11ea-863c-b4891e5febbc.png)
> > 不过还有点小问题，上图中的红色提示内容貌似每次启动mirai的时候都会弹出，无论是否以管理员的方式启动。

好的，这个将会修复
