### ISSUE TITLE
发语音文件后，文件被占用没释放

### ISSUE THREAD

**Issue by JoeAu** [iTXTech/mirai-native#84]
最新版1.9.0
程序产生写入data/record/voice.mp3，用[CQ:record,file=voice.mp3]发送语音后，日志发现已经转成arm格式发送成功。
程序再次产生新的语音文件写入data/record/voice.mp3，程序报错“文件被另一个进程占用”

**Comment by PeratX** [comment]
不按格式提交issue，直接关闭。
