### ISSUE TITLE
使用酷Q Ntive.SDK 接收匿名消息报错

### ISSUE THREAD

**Issue by m839336369** [iTXTech/mirai-native#86]
# 警告：请认真填写以下栏目，如果不符合要求，将直接被关闭。编辑完请删除此行。

**描述这个Bug**
清晰准确地表述这个Bug。

**复现步骤**
不载入插件没有事情，载入插件，无法断点到群成员消息接收，也就是群成员消息接收的事件之前便报错。
**期望的行为**
清晰准确地描述您期望的行为。

**截图和日志**
![image](https://user-images.githubusercontent.com/30934916/92557966-12a95d80-f2a0-11ea-87ad-34627c16e062.png)

**运行环境**
 - 操作系统：[例子：Windows 10 2004]
 - `mirai core` 版本：[例子：1.2.1]
 - `mirai console` 版本：[例子：1.0]
 - `mirai native` 版本：[例子：1.9.0]
 - `Java` 运行时版本：[例子：11.0.7 x86]

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
上传完整log

**Comment by m839336369** [comment]
> 上传完整log

[hs_err_pid11536.log](https://github.com/iTXTech/mirai-native/files/5192771/hs_err_pid11536.log)

**Comment by PeratX** [comment]
确实，这边匿名会默认把用户名当匿名参数发送，我还是先去掉吧

**Comment by m839336369** [comment]
> 确实，这边匿名会默认把用户名当匿名参数发送，我还是先去掉吧

好的，请问是下个版本更新，还是待会就更新呢?

**Comment by m839336369** [comment]
> 确实，这边匿名会默认把用户名当匿名参数发送，我还是先去掉吧

如果可以，我希望匿名消息的fromqq也可以获取到匿名的信息，毕竟逻辑处理如果区分为两个匿名逻辑和非匿名逻辑，增加了代码的重复

**Comment by PeratX** [comment]
fromqq，就是800000000，这个没办法

**Comment by m839336369** [comment]
> 800000000

ok，有QQ就行，我以为匿名fromqq=null
