### ISSUE TITLE
进群事件只能收到一次

### ISSUE THREAD

**Issue by m839336369** [iTXTech/mirai-native#87]
**描述这个Bug**
一个成员进群事件，在不装载任何插件的情况下，只会反馈一次，退群没问题，我使用同一个QQ，退群进群，只有mirai启动的第一次进群有反应，后续就不行了。

**复现步骤**

**期望的行为**
清晰准确地描述您期望的行为。

**截图和日志**
您必须提交相应的截图和 mirai console 日志

**运行环境**
 - 操作系统：[例子：Windows 10 2004]
 - `mirai core` 版本：[例子：1.2.1]
 - `mirai console` 版本：[例子：1.0]
 - `mirai native` 版本：[例子：1.9.0]
 - `Java` 运行时版本：[例子：11.0.7 x86]

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
mirai的问题，请向mirai反馈。

**Comment by m839336369** [comment]
> `mirai native`忠实的转发所有`mirai`事件，如果收不到，大概率是`mirai core`的问题。请悉知。

好的，我去提交mirai的issue

**Comment by PeratX** [comment]
https://github.com/mamoe/mirai/issues
