### ISSUE TITLE
望CQ码图片能支持base64格式

### ISSUE THREAD

**Issue by yfme01** [iTXTech/mirai-native#88]
以往酷Q是支持的，在移植以前的项目时发现无法部分图片发送

**特性描述**
特性如题

**Comment by PeratX** [comment]
请提供具体格式，问下来这个也是CQHTTP的功能

**Comment by yfme01** [comment]
> 请提供具体格式，问下来这个也是CQHTTP的功能

好像确实是cqhttp的，长这个样子`[CQ:image,url=base64://xxxxxxx]`

**Comment by PeratX** [comment]
不过也可以加上

**Comment by yfme01** [comment]
> 请提供具体格式，问下来这个也是CQHTTP的功能

好像确实是cqhttp的，长这个样子`[CQ:image,file=base64://xxxxxx]`

**Comment by yfme01** [comment]
> 对，CQHTTP已经实现了，那`mirai native`其实没必要实现

我就是在cqhttp上使用的，发现无法正常发送图片

**Comment by PeratX** [comment]
请提供完整的日志，查看CQHTTP是否创建了临时文件
