### ISSUE TITLE
图片或语音文件夹所写入 data 文件夹位置的问题

### ISSUE THREAD

**Issue by ricky8955555** [iTXTech/mirai-native#89]
**描述这个Bug**

1. 图片或语音文件夹的创建，尝试在 jre 目录下创建 data 文件夹
2. CQP.dll 写入到 console 指定的 data 目录下，并不存在这个问题

**复现步骤**

```cmd
@echo off
"C:\Program Files (x86)\Java\jre1.8.0_261\bin\java.exe" -cp ".\mirai-console-1.0-M4-dev-3-all.jar;mirai-console-pure-1.0-M4-dev-3-all.jar;mirai-core-qqandroid-1.2.2.jar" net.mamoe.mirai.console.pure.MiraiConsolePureLoader
pause
```

**期望的行为**

1. 图片或语音文件夹写入至 console 指定的 data 目录下

**截图和日志**

![image](https://user-images.githubusercontent.com/24487646/92986136-4926e880-f4eb-11ea-8453-e44e4164bc6b.png)

**运行环境**

 - 操作系统：Windows 10 1909
 - `mirai core` 版本：1.2.2
 - `mirai console` 版本：1.0-M4-dev-3
 - `mirai native` 版本：1.9.1
 - `Java` 运行时版本：1.8.0_261-b12

**Comment by PeratX** [comment]
**本文件夹专门用以兼容易语言编写的插件。**
详见：#82
