### ISSUE TITLE
JDK版本问题

### ISSUE THREAD

**Issue by AlexanderMisel** [iTXTech/mirai-native#90]
Mirai-Console现在要求的JDK版本为11+，但JDK 11+没有32位版本，mirai-native又只支持32位版本，应该怎么做？

**Comment by PeratX** [comment]
issue请务必按照格式提交。
JDK 11 32位可以在`https://adoptopenjdk.net/releases.html`下载。

**Comment by PeratX** [comment]
![image](https://user-images.githubusercontent.com/13656668/93010414-cb341180-f5be-11ea-8959-975a86730363.png)

**Comment by AlexanderMisel** [comment]
@PeratX 多谢。
