### ISSUE TITLE
PC端语音无法正常播放，移动端语音长度显示异常

### ISSUE THREAD

**Issue by mikualpha** [iTXTech/mirai-native#91]
**描述这个Bug**
使用C# Native框架开发的[语音插件](https://github.com/mikualpha/CQP-KanColleTime)发送约语音(mp3格式)时(如[这个约3s的音频](https://kcwiki.kcyuri.com/commons/c/c3/181a-0000.mp3))。
PC端无法正常播放(无论多长的音频文件，时长均显示为1s)。
移动端可以播放，但显示时长为36s(时长被放大约10倍，但实际播放是正常时长3s)。

**复现步骤**
下载[示例音频](https://kcwiki.kcyuri.com/commons/c/c3/181a-0000.mp3)，并用CQ码通过mirai-native直接发送即可。
如："[CQ:record,file=" + path + "]"

**期望的行为**
PC端应当可以正常获取时长，并可以播放。

**截图和日志**
日志显示转换成了amr格式，无乱码等异常情况。有需要可以后续补充。
PC端：![image](https://user-images.githubusercontent.com/24711249/93026456-aa100700-f638-11ea-88cc-9fcb325932c1.png)
移动端：![image](https://user-images.githubusercontent.com/24711249/93026497-e479a400-f638-11ea-8152-8aff843ba56d.png)
以上为同一条消息的两端不同视角。

**运行环境**
 - 操作系统：Windows Server 2012 R2
 - `mirai core` 版本：1.2.2
 - `mirai console` 版本：1.0-M4-dev-3
 - `mirai native` 版本：1.9.1
 - `Java` 运行时版本：1.8.0_252

**更多信息**
因为不太清楚对CQ码内容所指向的文件进行转换是由mirai-native进行还是传给了mirai-core，所以姑且先在这里提个issue问一下QAQ。

**Comment by PeratX** [comment]
mIra native不会对音频转码，请自行转换为amr或silk 格式，mirai core会把所有非silk 格式文件当成amr发送。
