### ISSUE TITLE
mirai无法正常接收单向好友的会话消息

### ISSUE THREAD

**Issue by Pika-Lee** [iTXTech/mirai-native#96]
**描述这个Bug**
在收到单向好友（只添加机器人为好友，但机器人未添加该用户为好友）的消息时，mirai无法接收并处理相关的消息。

**复现步骤**
1.将机器人的好友添加方式设置为无需验证问题或正确回答对验证问题。
2.添加机器人好友，自动与机器人建立单向好友关系。
3.私聊机器人发送一条消息。
4.mirai日志中未正常收到该消息，无法传递给插件处理相关事件。

**期望的行为**
希望mirai能正常收发单向好友、以及来源为群的临时会话消息。（双向好友太麻烦了，总不能让机器人一个个手动同意好友申请吧，而且好友列表数量本身也有上限）

**截图和日志**
![111](https://user-images.githubusercontent.com/23114990/93801780-1b713a80-fc75-11ea-8220-cb4dbc29fbf4.png)
![222](https://user-images.githubusercontent.com/23114990/93801791-20ce8500-fc75-11ea-95c2-37cb245dc456.png)

Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iter&^able>）

**运行环境**
 - 操作系统：[例子：Windows Server 2016]
 - `mirai core` 版本：[例子：1.3.0]
 - `mirai console` 版本：[例子：1.0-M4]
 - `mirai native` 版本：[例子：1.9.2]
 - `Java` 运行时版本：[例子：1.8.0 252]

**更多信息**
如果有其他相关的信息可以填写在此处。

**Comment by PeratX** [comment]
`mirai core`的问题，请向`mirai core`提交`issue`
